WITH SQ AS
(SELECT
    c.FSCL_QTR_IN_YR_NUM
    ,c.FSCL_YR_NUM
    ,org.RGN_DESCR
  -- Compute top box scores for each question
    ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.00000') END
   AS Q2_2_TB_Score
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.000') END
   AS Q2_1_TB_Score
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.000') END
   AS Q2_3_TB_Score
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.000') END
   AS Q2_4_TB_Score
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.000') END
   AS Q2_5_TB_Score
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.000') END
   AS Q2_6_TB_Score
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.000') END
   AS Q2_7_TB_Score

FROM APPDWH.AFT_CV_SRVY_RSPNS ce
  
  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
    --AND c.FSCL_PER_IN_YR_NUM IN (8,9)
    AND c.FSCL_YR_NUM IN (2015,2016,2017,2018)
    
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('US')
   
WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions
  AND ce.QSTN_ID NOT IN ('Q1','Q11') -- these questions are not in Customer Connection or Store Operations scores

GROUP BY
    c.FSCL_QTR_IN_YR_NUM
    ,c.FSCL_YR_NUM
    ,org.RGN_DESCR
), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    ,SQ.RGN_DESCR
    ,ROUND(SQ.Q2_2_TB_Score,3) AS CE_TB_CustConn
    ,ROUND(SQ.Q2_1_TB_Score,3) AS CE_TB_Speed
    ,ROUND(SQ.Q2_3_TB_Score,3) AS CE_TB_AbovBey
    ,ROUND(SQ.Q2_4_TB_Score,3) AS CE_TB_Accuracy
    ,ROUND(SQ.Q2_5_TB_Score,3) AS CE_TB_BevTaste
    ,ROUND(SQ.Q2_6_TB_Score,3) AS CE_TB_FoodTaste
    ,ROUND(SQ.Q2_7_TB_Score,3) AS CE_TB_Clean
    ,ROUND((AVG(SQ.Q2_1_TB_Score)+AVG(SQ.Q2_3_TB_Score)+AVG(SQ.Q2_4_TB_Score)+AVG(SQ.Q2_5_TB_Score)+AVG(SQ.Q2_6_TB_Score)+AVG(SQ.Q2_7_TB_Score))/6,3) AS CE_TB_StoreOps
FROM SQ
GROUP BY
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    ,SQ.RGN_DESCR
    ,SQ.Q2_2_TB_Score
    ,SQ.Q2_1_TB_Score
    ,SQ.Q2_3_TB_Score
    ,SQ.Q2_4_TB_Score
    ,SQ.Q2_5_TB_Score
    ,SQ.Q2_6_TB_Score
    ,SQ.Q2_7_TB_Score
Order BY
    SQ.RGN_DESCR DESC
    ,SQ.FSCL_YR_NUM ASC
    ,SQ.FSCL_QTR_IN_YR_NUM ASC)
SELECT
    SQ2.RGN_DESCR
    ,SQ2.FSCL_YR_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.CE_TB_CustConn*100 AS CE_TB_CustConn
    ,SQ2.CE_TB_Speed*100 AS CE_TB_Speed
    ,SQ2.CE_TB_AbovBey*100 AS CE_TB_AbovBey
    ,SQ2.CE_TB_Accuracy*100 AS CE_TB_Accuracy
    ,SQ2.CE_TB_BevTaste*100 AS CE_TB_BevTaste
    ,SQ2.CE_TB_FoodTaste*100 AS CE_TB_FoodTaste
    ,SQ2.CE_TB_Clean*100 AS CE_TB_Clean
    ,SQ2.CE_TB_StoreOps*100 AS CE_TB_StoreOps
FROM SQ2

ORDER BY SQ2.RGN_DESCR ASC
    ,SQ2.FSCL_YR_NUM ASC
    ,SQ2.FSCL_QTR_IN_YR_NUM ASC

