/*export as "CC-SP_by_store_cafe_only_FY18Q1-FY17Q4.csv"*/
/*
SELECT
   STORE_NUM
  ,FSCL_YR_NUM
  ,FSCL_QTR_IN_YR_NUM
  ,QSTN_ID
  ,ORD_MTHD_CD
  --,SUM(CASE WHEN RSPNS_ID = '7' THEN WEIGHT ELSE 0 END) AS TB_COUNT
  --,SUM(WEIGHT) AS RSPNS_COUNT
  ,SUM(CASE WHEN TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND RSPNS_ID = '7' THEN WEIGHT ELSE 0 END) AS PEAK_TB_COUNT
  ,SUM(CASE WHEN TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN WEIGHT ELSE 0 END) AS PEAK_RSPNS_COUNT
FROM (
SELECT DISTINCT
   sr.CASE_ID
  ,sr.GUID_USER_ID
  ,sr.RSPNS_DT
  ,sr.STORE_NUM
  ,sr.TRANS_DTM
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  
  ,COALESCE(w.WEIGHT_RT,1) AS WEIGHT
  
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  
  ,pi.TRANS_END_TM_KEY
  
  ,tt.MOBILE_ORD_PAY_IND
  ,tt.MOBILE_IND
  ,tt.ORD_MTHD_CD
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)
  
JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'
    AND st.DRIVE_THRU_IND = 0

LEFT JOIN APPOTHER.CUST_INS_WEIGHTS w
  ON sr.CASE_ID = w.CASE_ID

--/ Create universal transaction ID from survey table and use that to join to POS table
--/  Limit to U.S. and Canada and transactions after the survey began to improve performance /
JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    --AND pi.BUS_DT >= '01-SEP-15'
  
JOIN APPCA.D_POS_LINE_ITEM_TRANS_TYPE tt
  ON pi.POS_LINE_ITEM_TRANS_TYPE_KEY = tt.POS_LINE_ITEM_TRANS_TYPE_KEY

WHERE ((ca.FSCL_YR_NUM = 2017) OR (a.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 1))
  --AND ca.FSCL_QTR_IN_YR_NUM = 1
  AND sr.QSTN_ID IN ('Q2_2')
  AND sr.RSPNS_ID <> '9'
  --AND tt.ORD_MTHD_CD IN ('CAFE')
  --AND st.RGN_DESCR != 'PACIFIC NORTHWEST'
  --AND sr.STORE_NUM = 5798
)
GROUP BY
   STORE_NUM
  ,FSCL_YR_NUM
  ,FSCL_QTR_IN_YR_NUM
  ,QSTN_ID
  ,ORD_MTHD_CD
;
*/

/*
SELECT v.STORE_NUM, v.RGN_DESCR FROM  APPCA.D_STORE_VERS v
WHERE v.RGN_DESCR = 'PACIFIC NORTHWEST'
GROUP BY v.STORE_NUM, v.RGN_DESCR
*/


SELECT
   STORE_NUM
  ,FSCL_YR_NUM
  ,FSCL_QTR_IN_YR_NUM
  ,QSTN_ID
  ,ORD_MTHD_CD
  ,SUM(CASE WHEN RSPNS_ID = '7' THEN WEIGHT ELSE 0 END) AS TB_COUNT
  ,SUM(WEIGHT) AS RSPNS_COUNT
  ,SUM(CASE WHEN TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND RSPNS_ID = '7' THEN WEIGHT ELSE 0 END) AS PEAK_TB_COUNT
  ,SUM(CASE WHEN TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN WEIGHT ELSE 0 END) AS PEAK_RSPNS_COUNT
  ,DRIVE_THRU_IND
  
FROM (
SELECT DISTINCT
   sr.CASE_ID
  ,sr.GUID_USER_ID
  ,sr.RSPNS_DT
  ,sr.STORE_NUM
  ,sr.TRANS_DTM
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  
  ,COALESCE(w.WEIGHT_RT,1) AS WEIGHT
  
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  
  ,pi.TRANS_END_TM_KEY
  
  ,tt.MOBILE_ORD_PAY_IND
  ,tt.MOBILE_IND
  ,tt.ORD_MTHD_CD
  ,st.DRIVE_THRU_IND
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)
  
JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'
    --AND st.DRIVE_THRU_IND = 1 -- 0 for CAFE ONLY, 1 FOR DT

LEFT JOIN APPOTHER.CUST_INS_WEIGHTS w
  ON sr.CASE_ID = w.CASE_ID

-- Create universal transaction ID from survey table and use that to join to POS table
--  Limit to U.S. and Canada and transactions after the survey began to improve performance 
JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    AND pi.BUS_DT >= '01-SEP-15'
  
JOIN APPCA.D_POS_LINE_ITEM_TRANS_TYPE tt
  ON pi.POS_LINE_ITEM_TRANS_TYPE_KEY = tt.POS_LINE_ITEM_TRANS_TYPE_KEY

WHERE 
  (ca.FSCL_YR_NUM = 2017 OR (ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 1))
  --AND ca.FSCL_QTR_IN_YR_NUM = 3
  --ca.FSCL_YR_NUM = 2015 AND ca.FSCL_QTR_IN_YR_NUM = 4
  AND sr.QSTN_ID IN ('Q2_2')
  AND sr.RSPNS_ID <> '9'
  AND tt.ORD_MTHD_CD IN ('MOP','CAFE','OTW')
  --AND sr.STORE_NUM = 5798
)

GROUP BY
   STORE_NUM
  ,FSCL_YR_NUM
  ,FSCL_QTR_IN_YR_NUM
  ,QSTN_ID
  ,ORD_MTHD_CD
  ,DRIVE_THRU_IND
;




/*
SELECT DISTINCT
  COUNT(DISTINCT(sr.STORE_NUM)) AS storeN
  ,sr.QSTN_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,tt.ORD_MTHD_CD
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' THEN COALESCE(w.WEIGHT_RT,1) ELSE 0 END) AS TB_COUNT
  ,SUM(w.WEIGHT_RT) AS RSPNS_COUNT
  ,ROUND((SUM(CASE  WHEN sr.RSPNS_ID = '5' AND sr.QSTN_ID = 'Q1' THEN COALESCE(w.WEIGHT_RT,1) WHEN sr.RSPNS_ID = '7' THEN COALESCE(w.WEIGHT_RT,1) ELSE 0 END)) / SUM(COALESCE(w.WEIGHT_RT,1)),4) AS TB_SCORE

FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)

JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'

LEFT JOIN APPOTHER.CUST_INS_WEIGHTS w
  ON sr.CASE_ID = w.CASE_ID

--/ Create universal transaction ID from survey table and use that to join to POS table
--/  Limit to U.S. and Canada and transactions after the survey began to improve performance /
JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
      AND pi.BUS_DT >= '01-SEP-15'

JOIN APPCA.D_POS_LINE_ITEM_TRANS_TYPE tt
  ON pi.POS_LINE_ITEM_TRANS_TYPE_KEY = tt.POS_LINE_ITEM_TRANS_TYPE_KEY
  WHERE tt.ORD_MTHD_CD IN ('CAFE','MOP','OTW')
  AND sr.QSTN_ID IN ('Q2_2')
  AND sr.RSPNS_ID <> '9'
  AND ((ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 1) OR (ca.FSCL_YR_NUM = 2017))

GROUP BY
  sr.QSTN_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,tt.ORD_MTHD_CD
ORDER BY
  sr.QSTN_ID
  ,tt.ORD_MTHD_CD
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
*/




SELECT
  FSCL_YR_NUM
  ,FSCL_QTR_IN_YR_NUM
  ,QSTN_ID
  ,ORD_MTHD_CD
  ,SUM(CASE WHEN RSPNS_ID = '7' THEN WEIGHT ELSE 0 END) AS TB_COUNT
  ,SUM(WEIGHT) AS RSPNS_COUNT
  
FROM (
SELECT DISTINCT
   sr.CASE_ID
  ,sr.GUID_USER_ID
  ,sr.RSPNS_DT
  ,sr.STORE_NUM
  ,sr.TRANS_DTM
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  
  ,COALESCE(w.WEIGHT_RT,1) AS WEIGHT
  
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  
  ,pi.TRANS_END_TM_KEY
  
  --,tt.MOBILE_ORD_PAY_IND
  --,tt.MOBILE_IND
  ,tt.ORD_MTHD_CD
  --,st.DRIVE_THRU_IND
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)
  
JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'
    --AND st.DRIVE_THRU_IND = 1 -- 0 for CAFE ONLY, 1 FOR DT

LEFT JOIN APPOTHER.CUST_INS_WEIGHTS w
  ON sr.CASE_ID = w.CASE_ID

-- Create universal transaction ID from survey table and use that to join to POS table
--  Limit to U.S. and Canada and transactions after the survey began to improve performance 
JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    AND pi.BUS_DT >= '01-SEP-15'
  
JOIN APPCA.D_POS_LINE_ITEM_TRANS_TYPE tt
  ON pi.POS_LINE_ITEM_TRANS_TYPE_KEY = tt.POS_LINE_ITEM_TRANS_TYPE_KEY

WHERE 
  (ca.FSCL_YR_NUM = 2017 OR (ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 1))
  --AND ca.FSCL_QTR_IN_YR_NUM = 3
  --ca.FSCL_YR_NUM = 2015 AND ca.FSCL_QTR_IN_YR_NUM = 4
  AND sr.QSTN_ID IN ('Q2_2','Q2_1','Q2_3','Q2_4','Q2_5','Q2_6','Q2_7')
  AND sr.RSPNS_ID <> '9'
  AND tt.ORD_MTHD_CD IN ('MOP','CAFE','OTW')
  --AND sr.STORE_NUM = 5798
)

GROUP BY
   --STORE_NUM
  FSCL_YR_NUM
  ,FSCL_QTR_IN_YR_NUM
  ,QSTN_ID
  ,ORD_MTHD_CD
  --,DRIVE_THRU_IND
;






