--TOPLINE CE SCORES

WITH SQ AS
(SELECT
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ,ce.STORE_NUM

  -- Compute top box scores for each question
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.0000') END
   AS CC
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.0000') END
   AS SPEED
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.0000') END
   AS ABVBEYND
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.0000') END
   AS ACCURACY
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.0000') END
   AS BEVTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.0000') END
   AS FOODTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.0000') END
   AS CLEAN

FROM APPDWH.AFT_CV_SRVY_RSPNS ce

  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
      AND c.FSCL_YR_NUM IN (2017,2018)
      AND c.FSCL_QTR_IN_YR_NUM IN (3)
      
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         --AND org.OWNR_TYPE_CD IN ('CO')
         --AND org.CNTRY_CD IN ('CA')

WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions
  AND ce.STORE_NUM IN (4464,15545,187)

GROUP BY
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ,ce.STORE_NUM), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    ,SQ.STORE_NUM
    ,SQ.CC
    ,SQ.SPEED
    ,SQ.ABVBEYND
    ,SQ.ACCURACY
    ,SQ.BEVTASTE
    ,SQ.FOODTASTE   
    ,SQ.CLEAN
    ,ROUND((AVG(SQ.SPEED)+AVG(SQ.ABVBEYND)+AVG(SQ.ACCURACY)+AVG(SQ.BEVTASTE)+AVG(SQ.FOODTASTE)+AVG(SQ.CLEAN))/6,4) AS STOREOPS
FROM SQ
GROUP BY
    SQ.FSCL_YR_NUM
    ,SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.CC
    ,SQ.SPEED
    ,SQ.ABVBEYND
    ,SQ.ACCURACY
    ,SQ.BEVTASTE
    ,SQ.FOODTASTE   
    ,SQ.CLEAN
    ,SQ.STORE_NUM
Order BY
    SQ.STORE_NUM
    ,SQ.FSCL_YR_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.CC
    ,SQ2.CC - lag(SQ2.CC) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM) AS CC_YOY
    ,SQ2.STOREOPS
    ,SQ2.STOREOPS - lag(SQ2.STOREOPS) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM) AS STOREOPS_YOY
    ,SQ2.SPEED
    ,SQ2.SPEED - lag(SQ2.SPEED) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS SPEED_YOY
    ,SQ2.ABVBEYND
    ,SQ2.ABVBEYND - lag(SQ2.ABVBEYND) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS ABVBEYND_YOY
    ,SQ2.ACCURACY
    ,SQ2.ACCURACY - lag(SQ2.ACCURACY) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS ACCURACY_YOY
    ,SQ2.BEVTASTE
    ,SQ2.BEVTASTE - lag(SQ2.BEVTASTE) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS BEVTASTE_YOY
    ,SQ2.FOODTASTE
    ,SQ2.FOODTASTE - lag(SQ2.FOODTASTE) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS FOODTASTE_YOY
    ,SQ2.CLEAN
    ,SQ2.CLEAN - lag(SQ2.CLEAN) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS CLEAN_YOY

FROM SQ2
GROUP BY 
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.CC
    ,SQ2.STOREOPS
    ,SQ2.SPEED
    ,SQ2.ABVBEYND
    ,SQ2.ACCURACY
    ,SQ2.BEVTASTE
    ,SQ2.FOODTASTE   
    ,SQ2.CLEAN   
    
ORDER BY
    SQ2.STORE_NUM
    ,SQ2.FSCL_YR_NUM DESC)
SELECT
    SQ3.STORE_NUM
    ,SQ3.FSCL_YR_NUM
    ,SQ3.CC
    ,SQ3.CC_YOY
    ,SQ3.STOREOPS
    ,SQ3.STOREOPS_YOY
    ,SQ3.SPEED    
    ,SQ3.SPEED_YOY
    ,SQ3.ABVBEYND
    ,SQ3.ABVBEYND_YOY
    ,SQ3.ACCURACY
    ,SQ3.ACCURACY_YOY
    ,SQ3.BEVTASTE
    ,SQ3.BEVTASTE_YOY
    ,SQ3.FOODTASTE   
    ,SQ3.FOODTASTE_YOY  
    ,SQ3.CLEAN 
    ,SQ3.CLEAN_YOY 
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
    
    
    
--PEAK CE SCORES

WITH SQ AS
(SELECT
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ,ce.STORE_NUM

  -- Compute top box scores for each question
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKCC
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKSPEED
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKABVBEYND
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKACCURACY
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKBEVTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKFOODTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKCLEAN

FROM APPDWH.AFT_CV_SRVY_RSPNS ce

  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
      AND c.FSCL_YR_NUM IN (2017,2018)
      AND c.FSCL_QTR_IN_YR_NUM IN (3)
      
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')

WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions
  AND ce.STORE_NUM IN (4464,15545,187)
  AND (TO_CHAR(ce.TRANS_DTM, 'HH24') >=7 AND TO_CHAR(ce.TRANS_DTM, 'HH24') < 11)

GROUP BY
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ,ce.STORE_NUM), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    ,SQ.STORE_NUM
    ,SQ.PEAKCC
    ,SQ.PEAKSPEED
    ,SQ.PEAKABVBEYND
    ,SQ.PEAKACCURACY
    ,SQ.PEAKBEVTASTE
    ,SQ.PEAKFOODTASTE   
    ,SQ.PEAKCLEAN
    ,ROUND((AVG(SQ.PEAKSPEED)+AVG(SQ.PEAKABVBEYND)+AVG(SQ.PEAKACCURACY)+AVG(SQ.PEAKBEVTASTE)+AVG(SQ.PEAKFOODTASTE)+AVG(SQ.PEAKCLEAN))/6,4) AS PEAKSTOREOPS
FROM SQ
GROUP BY
    SQ.FSCL_YR_NUM
    ,SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.PEAKCC
    ,SQ.PEAKSPEED
    ,SQ.PEAKABVBEYND
    ,SQ.PEAKACCURACY
    ,SQ.PEAKBEVTASTE
    ,SQ.PEAKFOODTASTE   
    ,SQ.PEAKCLEAN
    ,SQ.STORE_NUM
Order BY
    SQ.STORE_NUM
    ,SQ.FSCL_YR_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PEAKCC
    ,SQ2.PEAKCC - lag(SQ2.PEAKCC) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKCC_YOY
    ,SQ2.PEAKSTOREOPS
    ,SQ2.PEAKSTOREOPS - lag(SQ2.PEAKSTOREOPS) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKSTOREOPS_YOY
    ,SQ2.PEAKSPEED
    ,SQ2.PEAKSPEED - lag(SQ2.PEAKSPEED) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKSPEED_YOY
    ,SQ2.PEAKABVBEYND
    ,SQ2.PEAKABVBEYND - lag(SQ2.PEAKABVBEYND) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKABVBEYND_YOY
    ,SQ2.PEAKACCURACY
    ,SQ2.PEAKACCURACY - lag(SQ2.PEAKACCURACY) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKACCURACY_YOY
    ,SQ2.PEAKBEVTASTE
    ,SQ2.PEAKBEVTASTE - lag(SQ2.PEAKBEVTASTE)over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKBEVTASTE_YOY
    ,SQ2.PEAKFOODTASTE
    ,SQ2.PEAKFOODTASTE - lag(SQ2.PEAKFOODTASTE) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKFOODTASTE_YOY
    ,SQ2.PEAKCLEAN
    ,SQ2.PEAKCLEAN - lag(SQ2.PEAKCLEAN) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PEAKCLEAN_YOY

FROM SQ2
GROUP BY 
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PEAKCC
    ,SQ2.PEAKSTOREOPS
    ,SQ2.PEAKSPEED
    ,SQ2.PEAKABVBEYND
    ,SQ2.PEAKACCURACY
    ,SQ2.PEAKBEVTASTE
    ,SQ2.PEAKFOODTASTE   
    ,SQ2.PEAKCLEAN   
    
ORDER BY
    SQ2.STORE_NUM
    ,SQ2.FSCL_YR_NUM DESC)
SELECT
    SQ3.STORE_NUM
    ,SQ3.PEAKCC
    ,SQ3.PEAKCC_YOY
    ,SQ3.PEAKSTOREOPS
    ,SQ3.PEAKSTOREOPS_YOY
    ,SQ3.PEAKSPEED    
    ,SQ3.PEAKSPEED_YOY
    ,SQ3.PEAKABVBEYND
    ,SQ3.PEAKABVBEYND_YOY
    ,SQ3.PEAKACCURACY
    ,SQ3.PEAKACCURACY_YOY
    ,SQ3.PEAKBEVTASTE
    ,SQ3.PEAKBEVTASTE_YOY
    ,SQ3.PEAKFOODTASTE   
    ,SQ3.PEAKFOODTASTE_YOY  
    ,SQ3.PEAKCLEAN 
    ,SQ3.PEAKCLEAN_YOY 
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
    

--PM CE SCORES

WITH SQ AS
(SELECT
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ,ce.STORE_NUM

  -- Compute top box scores for each question
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.0000') END
   AS PMCC
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.0000') END
   AS PMSPEED
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.0000') END
   AS PMABVBEYND
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.0000') END
   AS PMACCURACY
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.0000') END
   AS PMBEVTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.0000') END
   AS PMFOODTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.0000') END
   AS PMCLEAN

FROM APPDWH.AFT_CV_SRVY_RSPNS ce

  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
      AND c.FSCL_YR_NUM IN (2017,2018)
      AND c.FSCL_QTR_IN_YR_NUM IN (3)
      
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')

WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions
  AND ce.STORE_NUM IN (4464,15545,187)
  AND (TO_CHAR(ce.TRANS_DTM, 'HH24') >=14 AND TO_CHAR(ce.TRANS_DTM, 'HH24') < 16)

GROUP BY
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ,ce.STORE_NUM), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    ,SQ.STORE_NUM
    ,SQ.PMCC
    ,SQ.PMSPEED
    ,SQ.PMABVBEYND
    ,SQ.PMACCURACY
    ,SQ.PMBEVTASTE
    ,SQ.PMFOODTASTE   
    ,SQ.PMCLEAN
    ,ROUND((AVG(SQ.PMSPEED)+AVG(SQ.PMABVBEYND)+AVG(SQ.PMACCURACY)+AVG(SQ.PMBEVTASTE)+AVG(SQ.PMFOODTASTE)+AVG(SQ.PMCLEAN))/6,4) AS PMSTOREOPS
FROM SQ
GROUP BY
    SQ.FSCL_YR_NUM
    ,SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.PMCC
    ,SQ.PMSPEED
    ,SQ.PMABVBEYND
    ,SQ.PMACCURACY
    ,SQ.PMBEVTASTE
    ,SQ.PMFOODTASTE   
    ,SQ.PMCLEAN
    ,SQ.STORE_NUM
Order BY
    SQ.STORE_NUM
    ,SQ.FSCL_YR_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PMCC
    ,SQ2.PMCC - lag(SQ2.PMCC) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMCC_YOY
    ,SQ2.PMSTOREOPS
    ,SQ2.PMSTOREOPS - lag(SQ2.PMSTOREOPS) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMSTOREOPS_YOY
    ,SQ2.PMSPEED
    ,SQ2.PMSPEED - lag(SQ2.PMSPEED) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMSPEED_YOY
    ,SQ2.PMABVBEYND
    ,SQ2.PMABVBEYND - lag(SQ2.PMABVBEYND) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMABVBEYND_YOY
    ,SQ2.PMACCURACY
    ,SQ2.PMACCURACY - lag(SQ2.PMACCURACY) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMACCURACY_YOY
    ,SQ2.PMBEVTASTE
    ,SQ2.PMBEVTASTE - lag(SQ2.PMBEVTASTE)over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMBEVTASTE_YOY
    ,SQ2.PMFOODTASTE
    ,SQ2.PMFOODTASTE - lag(SQ2.PMFOODTASTE) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMFOODTASTE_YOY
    ,SQ2.PMCLEAN
    ,SQ2.PMCLEAN - lag(SQ2.PMCLEAN) over(partition by SQ2.STORE_NUM order by SQ2.FSCL_YR_NUM)  AS PMCLEAN_YOY

FROM SQ2
GROUP BY 
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PMCC
    ,SQ2.PMSTOREOPS
    ,SQ2.PMSPEED
    ,SQ2.PMABVBEYND
    ,SQ2.PMACCURACY
    ,SQ2.PMBEVTASTE
    ,SQ2.PMFOODTASTE   
    ,SQ2.PMCLEAN   
    
ORDER BY
    SQ2.STORE_NUM
    ,SQ2.FSCL_YR_NUM DESC)
SELECT
    SQ3.STORE_NUM
    ,SQ3.PMCC
    ,SQ3.PMCC_YOY
    ,SQ3.PMSTOREOPS
    ,SQ3.PMSTOREOPS_YOY
    ,SQ3.PMSPEED    
    ,SQ3.PMSPEED_YOY
    ,SQ3.PMABVBEYND
    ,SQ3.PMABVBEYND_YOY
    ,SQ3.PMACCURACY
    ,SQ3.PMACCURACY_YOY
    ,SQ3.PMBEVTASTE
    ,SQ3.PMBEVTASTE_YOY
    ,SQ3.PMFOODTASTE   
    ,SQ3.PMFOODTASTE_YOY  
    ,SQ3.PMCLEAN 
    ,SQ3.PMCLEAN_YOY 
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
    



/*customer transaction count by hour (and daypart indicator)*/
WITH SQ AS
(SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.SALE_HOUR 
  ,f.STORE_NUMBER
  ,f.BUSINESS_DATE
  ,SUM(f.CUTOMER_TRANSACTION_COUNT) AS "TRANS"
      ,(CASE WHEN f.SALE_HOUR  < 110000 THEN 1 -- am
        WHEN f.SALE_HOUR  >=110000 AND f.SALE_HOUR  < 140000 THEN 2 -- midday
        WHEN f.SALE_HOUR  >=140000 AND f.SALE_HOUR  < 160000 THEN 3 -- pm
        WHEN f.SALE_HOUR  >=160000 THEN 4 -- evening
        ELSE 0 
        END) AS DAY_PART
FROM APPBUS.AFT_POS_INTL_HDR_VW f
    INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 3
  INNER JOIN APPDWH.ADT_STORE org
      ON f.STORE_NUMBER = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')
         AND f.STORE_NUMBER IN (4464,15545,187)
GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.STORE_NUMBER
  ,f.BUSINESS_DATE
  ,f.SALE_HOUR)
  SELECT SQ.FSCL_YR_NUM
  , SQ.FSCL_QTR_IN_YR_NUM
  , SQ.DAY_PART
  , SQ.STORE_NUMBER
  , SUM(SQ.TRANS) AS TRANS
  , COUNT(UNIQUE(SQ.BUSINESS_DATE)) AS DAY_COUNT
  , COUNT(UNIQUE(SQ.STORE_NUMBER)) AS STORE_COUNT
  , COUNT(UNIQUE(SQ.BUSINESS_DATE))*COUNT(UNIQUE(SQ.STORE_NUMBER)) AS ACTIVE_STORE_DAY_COUNT
  , ROUND(SUM(SQ.TRANS)/(COUNT(UNIQUE(SQ.BUSINESS_DATE))*COUNT(UNIQUE(SQ.STORE_NUMBER))),0) AS COSD
  FROM SQ
  GROUP BY SQ.FSCL_YR_NUM
  , SQ.FSCL_QTR_IN_YR_NUM
  , SQ.DAY_PART
  , SQ.STORE_NUMBER
  ORDER BY SQ.DAY_PART
  , SQ.STORE_NUMBER
  
  
--Channel mix by store
--416

SELECT
   ss.STORE_NUM
  ,ss.DRIVE_THRU_IND
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,COUNT(DISTINCT tr.TRANS_ID) AS TTL_TRANS_CNT
  --,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) AS MOP_TRANS_CNT
  --,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) AS OTW_TRANS_CNT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) / COUNT(DISTINCT tr.TRANS_ID),4)*100 AS MOP_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END),4)*100 AS PEAK_MOP_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 AND ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 THEN tr.TRANS_ID END),4)*100 AS PM_MOP_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) / COUNT(DISTINCT tr.TRANS_ID),4)*100 AS OTW_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END),4)*100 AS PEAK_OTW_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 AND ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 THEN tr.TRANS_ID END),4)*100 AS PM_OTW_PCT
  
FROM APPCA.F_POS_HDR tr

INNER JOIN D_POS_HDR_TRANS_TYPE ty
  ON tr.POS_HDR_TRANS_TYPE_KEY = ty.POS_HDR_TRANS_TYPE_KEY
  
INNER JOIN APPCA.D_STORE_VERS ss
  ON ss.STORE_VERS_KEY = tr.STORE_VERS_KEY
  
INNER JOIN APPCA.D_CAL ca
  ON tr.BUS_DT = ca.CAL_DT

WHERE tr.CNTRY_CD = 'CA'
  AND ss.OWNR_TYPE_CD = 'CO'
  AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 3
  AND ss.STORE_NUM IN (4464,15545,187)

GROUP BY
   ss.STORE_NUM
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,ss.DRIVE_THRU_IND
  

--415
--SM Stability

SELECT
s.FSCL_PER_BEG_DT,
s.ORG_UNIT_NUM,
s.STORE_NUM,
s.SM1YRSTABLE,
s.SM2YRSTABLE

FROM LRIVERS.STOREMANAGERSTABILITY s

/* get most recent rolling 12 report (table updates once per month) */
WHERE s.FSCL_PER_BEG_DT = (select max(FSCL_PER_BEG_DT) from LRIVERS.STOREMANAGERSTABILITY)

AND s.STORE_NUM IN (4464,15545,187)

GROUP BY
s.FSCL_PER_BEG_DT,
s.ORG_UNIT_NUM,
s.STORE_NUM,
s.SM1YRSTABLE,
s.SM2YRSTABLE























--TOPLINE CE SCORES -- MID-AMERICA

WITH SQ AS
(SELECT
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  --,ce.STORE_NUM

  -- Compute top box scores for each question
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.0000') END
   AS CC
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.0000') END
   AS SPEED
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.0000') END
   AS ABVBEYND
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.0000') END
   AS ACCURACY
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.0000') END
   AS BEVTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.0000') END
   AS FOODTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.0000') END
   AS CLEAN

FROM APPDWH.AFT_CV_SRVY_RSPNS ce

  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
      AND c.FSCL_YR_NUM IN (2017,2018)
      AND c.FSCL_QTR_IN_YR_NUM IN (3)
      
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')
         AND org.AREA_DESCR = 'British Columbia 3'

WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions

GROUP BY
   c.FSCL_YR_NUM
  --,ce.STORE_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  ), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    --,SQ.STORE_NUM
    ,SQ.CC
    ,SQ.SPEED
    ,SQ.ABVBEYND
    ,SQ.ACCURACY
    ,SQ.BEVTASTE
    ,SQ.FOODTASTE   
    ,SQ.CLEAN
    ,ROUND((AVG(SQ.SPEED)+AVG(SQ.ABVBEYND)+AVG(SQ.ACCURACY)+AVG(SQ.BEVTASTE)+AVG(SQ.FOODTASTE)+AVG(SQ.CLEAN))/6,4) AS STOREOPS
FROM SQ
GROUP BY
    SQ.FSCL_YR_NUM
    ,SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.CC
    ,SQ.SPEED
    ,SQ.ABVBEYND
    ,SQ.ACCURACY
    ,SQ.BEVTASTE
    ,SQ.FOODTASTE   
    ,SQ.CLEAN
    --,SQ.STORE_NUM
Order BY
    --SQ.STORE_NUM
    SQ.FSCL_YR_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    --,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.CC
    ,SQ2.CC - lag(SQ2.CC) over(order by SQ2.FSCL_YR_NUM) AS CC_YOY
    ,SQ2.STOREOPS
    ,SQ2.STOREOPS - lag(SQ2.STOREOPS) over(order by SQ2.FSCL_YR_NUM) AS STOREOPS_YOY
    ,SQ2.SPEED
    ,SQ2.SPEED - lag(SQ2.SPEED) over(order by SQ2.FSCL_YR_NUM)  AS SPEED_YOY
    ,SQ2.ABVBEYND
    ,SQ2.ABVBEYND - lag(SQ2.ABVBEYND) over(order by SQ2.FSCL_YR_NUM)  AS ABVBEYND_YOY
    ,SQ2.ACCURACY
    ,SQ2.ACCURACY - lag(SQ2.ACCURACY) over(order by SQ2.FSCL_YR_NUM)  AS ACCURACY_YOY
    ,SQ2.BEVTASTE
    ,SQ2.BEVTASTE - lag(SQ2.BEVTASTE) over(order by SQ2.FSCL_YR_NUM)  AS BEVTASTE_YOY
    ,SQ2.FOODTASTE
    ,SQ2.FOODTASTE - lag(SQ2.FOODTASTE) over(order by SQ2.FSCL_YR_NUM)  AS FOODTASTE_YOY
    ,SQ2.CLEAN
    ,SQ2.CLEAN - lag(SQ2.CLEAN) over(order by SQ2.FSCL_YR_NUM)  AS CLEAN_YOY

FROM SQ2
GROUP BY 
    SQ2.FSCL_YR_NUM
    --,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.CC
    ,SQ2.STOREOPS
    ,SQ2.SPEED
    ,SQ2.ABVBEYND
    ,SQ2.ACCURACY
    ,SQ2.BEVTASTE
    ,SQ2.FOODTASTE   
    ,SQ2.CLEAN   
    
ORDER BY
    --SQ2.STORE_NUM
    SQ2.FSCL_YR_NUM DESC)
SELECT
    --SQ3.STORE_NUM
    SQ3.FSCL_YR_NUM
    ,SQ3.CC
    ,SQ3.CC_YOY
    ,SQ3.STOREOPS
    ,SQ3.STOREOPS_YOY
    ,SQ3.SPEED    
    ,SQ3.SPEED_YOY
    ,SQ3.ABVBEYND
    ,SQ3.ABVBEYND_YOY
    ,SQ3.ACCURACY
    ,SQ3.ACCURACY_YOY
    ,SQ3.BEVTASTE
    ,SQ3.BEVTASTE_YOY
    ,SQ3.FOODTASTE   
    ,SQ3.FOODTASTE_YOY  
    ,SQ3.CLEAN 
    ,SQ3.CLEAN_YOY 
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
    
    
    
--PEAK CE SCORES

WITH SQ AS
(SELECT
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  --,ce.STORE_NUM

  -- Compute top box scores for each question
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKCC
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKSPEED
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKABVBEYND
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKACCURACY
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKBEVTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKFOODTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.0000') END
   AS PEAKCLEAN

FROM APPDWH.AFT_CV_SRVY_RSPNS ce

  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
      AND c.FSCL_YR_NUM IN (2017,2018)
      AND c.FSCL_QTR_IN_YR_NUM IN (3)
      
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')
         AND org.AREA_DESCR = 'British Columbia 3'

WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions
  AND (TO_CHAR(ce.TRANS_DTM, 'HH24') >=7 AND TO_CHAR(ce.TRANS_DTM, 'HH24') < 11)

GROUP BY
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  --,ce.STORE_NUM
  ), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    --,SQ.STORE_NUM
    ,SQ.PEAKCC
    ,SQ.PEAKSPEED
    ,SQ.PEAKABVBEYND
    ,SQ.PEAKACCURACY
    ,SQ.PEAKBEVTASTE
    ,SQ.PEAKFOODTASTE   
    ,SQ.PEAKCLEAN
    ,ROUND((AVG(SQ.PEAKSPEED)+AVG(SQ.PEAKABVBEYND)+AVG(SQ.PEAKACCURACY)+AVG(SQ.PEAKBEVTASTE)+AVG(SQ.PEAKFOODTASTE)+AVG(SQ.PEAKCLEAN))/6,4) AS PEAKSTOREOPS
FROM SQ
GROUP BY
    SQ.FSCL_YR_NUM
    ,SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.PEAKCC
    ,SQ.PEAKSPEED
    ,SQ.PEAKABVBEYND
    ,SQ.PEAKACCURACY
    ,SQ.PEAKBEVTASTE
    ,SQ.PEAKFOODTASTE   
    ,SQ.PEAKCLEAN
    --,SQ.STORE_NUM
Order BY
    --SQ.STORE_NUM
    SQ.FSCL_YR_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    --,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PEAKCC
    ,SQ2.PEAKCC - lag(SQ2.PEAKCC) over(order by SQ2.FSCL_YR_NUM)  AS PEAKCC_YOY
    ,SQ2.PEAKSTOREOPS
    ,SQ2.PEAKSTOREOPS - lag(SQ2.PEAKSTOREOPS) over(order by SQ2.FSCL_YR_NUM)  AS PEAKSTOREOPS_YOY
    ,SQ2.PEAKSPEED
    ,SQ2.PEAKSPEED - lag(SQ2.PEAKSPEED) over(order by SQ2.FSCL_YR_NUM)  AS PEAKSPEED_YOY
    ,SQ2.PEAKABVBEYND
    ,SQ2.PEAKABVBEYND - lag(SQ2.PEAKABVBEYND) over(order by SQ2.FSCL_YR_NUM)  AS PEAKABVBEYND_YOY
    ,SQ2.PEAKACCURACY
    ,SQ2.PEAKACCURACY - lag(SQ2.PEAKACCURACY) over(order by SQ2.FSCL_YR_NUM)  AS PEAKACCURACY_YOY
    ,SQ2.PEAKBEVTASTE
    ,SQ2.PEAKBEVTASTE - lag(SQ2.PEAKBEVTASTE)over(order by SQ2.FSCL_YR_NUM)  AS PEAKBEVTASTE_YOY
    ,SQ2.PEAKFOODTASTE
    ,SQ2.PEAKFOODTASTE - lag(SQ2.PEAKFOODTASTE) over(order by SQ2.FSCL_YR_NUM)  AS PEAKFOODTASTE_YOY
    ,SQ2.PEAKCLEAN
    ,SQ2.PEAKCLEAN - lag(SQ2.PEAKCLEAN) over(order by SQ2.FSCL_YR_NUM)  AS PEAKCLEAN_YOY

FROM SQ2
GROUP BY 
    SQ2.FSCL_YR_NUM
    --,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PEAKCC
    ,SQ2.PEAKSTOREOPS
    ,SQ2.PEAKSPEED
    ,SQ2.PEAKABVBEYND
    ,SQ2.PEAKACCURACY
    ,SQ2.PEAKBEVTASTE
    ,SQ2.PEAKFOODTASTE   
    ,SQ2.PEAKCLEAN   
    
ORDER BY
    --SQ2.STORE_NUM
    SQ2.FSCL_YR_NUM DESC)
SELECT
    --SQ3.STORE_NUM
    SQ3.PEAKCC
    ,SQ3.PEAKCC_YOY
    ,SQ3.PEAKSTOREOPS
    ,SQ3.PEAKSTOREOPS_YOY
    ,SQ3.PEAKSPEED    
    ,SQ3.PEAKSPEED_YOY
    ,SQ3.PEAKABVBEYND
    ,SQ3.PEAKABVBEYND_YOY
    ,SQ3.PEAKACCURACY
    ,SQ3.PEAKACCURACY_YOY
    ,SQ3.PEAKBEVTASTE
    ,SQ3.PEAKBEVTASTE_YOY
    ,SQ3.PEAKFOODTASTE   
    ,SQ3.PEAKFOODTASTE_YOY  
    ,SQ3.PEAKCLEAN 
    ,SQ3.PEAKCLEAN_YOY 
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
    
 

   
--PM CE SCORES

WITH SQ AS
(SELECT
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  --,ce.STORE_NUM

  -- Compute top box scores for each question
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_2' THEN ce.QSTN_ID END),'0.0000') END
   AS PMCC
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_1' THEN ce.QSTN_ID END),'0.0000') END
   AS PMSPEED
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_3' THEN ce.QSTN_ID END),'0.0000') END
   AS PMABVBEYND
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_4' THEN ce.QSTN_ID END),'0.0000') END
   AS PMACCURACY
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_5' THEN ce.QSTN_ID END),'0.0000') END
   AS PMBEVTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_6' THEN ce.QSTN_ID END),'0.0000') END
   AS PMFOODTASTE
  ,CASE WHEN COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END) = 0 THEN NULL
   ELSE TO_CHAR(SUM(CASE WHEN ce.RSPNS_ID = '7' AND ce.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END)
    / COUNT(CASE WHEN ce.QSTN_ID = 'Q2_7' THEN ce.QSTN_ID END),'0.0000') END
   AS PMCLEAN

FROM APPDWH.AFT_CV_SRVY_RSPNS ce

  INNER JOIN APPDWH.ADT_CAL c
    ON TRUNC(ce.TRANS_DTM) = c.CAL_DT
      AND c.FSCL_YR_NUM IN (2017,2018)
      AND c.FSCL_QTR_IN_YR_NUM IN (3)
      
  INNER JOIN APPDWH.ADT_STORE org
      ON ce.STORE_NUM = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')
         AND org.AREA_DESCR = 'British Columbia 3'

WHERE ce.RSPNS_ID <> '9'  -- rspns_id = 9 for unanswered questions
  AND (TO_CHAR(ce.TRANS_DTM, 'HH24') >=14 AND TO_CHAR(ce.TRANS_DTM, 'HH24') < 16)

GROUP BY
   c.FSCL_YR_NUM
  ,c.FSCL_QTR_IN_YR_NUM
  --,ce.STORE_NUM
  ), SQ2 AS(
SELECT     
    SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.FSCL_YR_NUM
    --,SQ.STORE_NUM
    ,SQ.PMCC
    ,SQ.PMSPEED
    ,SQ.PMABVBEYND
    ,SQ.PMACCURACY
    ,SQ.PMBEVTASTE
    ,SQ.PMFOODTASTE   
    ,SQ.PMCLEAN
    ,ROUND((AVG(SQ.PMSPEED)+AVG(SQ.PMABVBEYND)+AVG(SQ.PMACCURACY)+AVG(SQ.PMBEVTASTE)+AVG(SQ.PMFOODTASTE)+AVG(SQ.PMCLEAN))/6,4) AS PMSTOREOPS
FROM SQ
GROUP BY
    SQ.FSCL_YR_NUM
    ,SQ.FSCL_QTR_IN_YR_NUM
    ,SQ.PMCC
    ,SQ.PMSPEED
    ,SQ.PMABVBEYND
    ,SQ.PMACCURACY
    ,SQ.PMBEVTASTE
    ,SQ.PMFOODTASTE   
    ,SQ.PMCLEAN
    --,SQ.STORE_NUM
Order BY
    --SQ.STORE_NUM
    SQ.FSCL_YR_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    --,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PMCC
    ,SQ2.PMCC - lag(SQ2.PMCC) over(order by SQ2.FSCL_YR_NUM)  AS PMCC_YOY
    ,SQ2.PMSTOREOPS
    ,SQ2.PMSTOREOPS - lag(SQ2.PMSTOREOPS) over(order by SQ2.FSCL_YR_NUM)  AS PMSTOREOPS_YOY
    ,SQ2.PMSPEED
    ,SQ2.PMSPEED - lag(SQ2.PMSPEED) over(order by SQ2.FSCL_YR_NUM)  AS PMSPEED_YOY
    ,SQ2.PMABVBEYND
    ,SQ2.PMABVBEYND - lag(SQ2.PMABVBEYND) over(order by SQ2.FSCL_YR_NUM)  AS PMABVBEYND_YOY
    ,SQ2.PMACCURACY
    ,SQ2.PMACCURACY - lag(SQ2.PMACCURACY) over(order by SQ2.FSCL_YR_NUM)  AS PMACCURACY_YOY
    ,SQ2.PMBEVTASTE
    ,SQ2.PMBEVTASTE - lag(SQ2.PMBEVTASTE)over(order by SQ2.FSCL_YR_NUM)  AS PMBEVTASTE_YOY
    ,SQ2.PMFOODTASTE
    ,SQ2.PMFOODTASTE - lag(SQ2.PMFOODTASTE) over(order by SQ2.FSCL_YR_NUM)  AS PMFOODTASTE_YOY
    ,SQ2.PMCLEAN
    ,SQ2.PMCLEAN - lag(SQ2.PMCLEAN) over(order by SQ2.FSCL_YR_NUM)  AS PMCLEAN_YOY

FROM SQ2
GROUP BY 
    SQ2.FSCL_YR_NUM
    --,SQ2.STORE_NUM
    ,SQ2.FSCL_QTR_IN_YR_NUM
    ,SQ2.PMCC
    ,SQ2.PMSTOREOPS
    ,SQ2.PMSPEED
    ,SQ2.PMABVBEYND
    ,SQ2.PMACCURACY
    ,SQ2.PMBEVTASTE
    ,SQ2.PMFOODTASTE   
    ,SQ2.PMCLEAN   
    
ORDER BY
    --SQ2.STORE_NUM
    SQ2.FSCL_YR_NUM DESC)
SELECT
    --SQ3.STORE_NUM
    SQ3.PMCC
    ,SQ3.PMCC_YOY
    ,SQ3.PMSTOREOPS
    ,SQ3.PMSTOREOPS_YOY
    ,SQ3.PMSPEED    
    ,SQ3.PMSPEED_YOY
    ,SQ3.PMABVBEYND
    ,SQ3.PMABVBEYND_YOY
    ,SQ3.PMACCURACY
    ,SQ3.PMACCURACY_YOY
    ,SQ3.PMBEVTASTE
    ,SQ3.PMBEVTASTE_YOY
    ,SQ3.PMFOODTASTE   
    ,SQ3.PMFOODTASTE_YOY  
    ,SQ3.PMCLEAN 
    ,SQ3.PMCLEAN_YOY 
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
    
    
/*customer transaction count by hour (and daypart indicator)*/
WITH SQ AS
(SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.SALE_HOUR 
  ,f.STORE_NUMBER
  ,f.BUSINESS_DATE
  ,SUM(f.CUTOMER_TRANSACTION_COUNT) AS "TRANS"
      ,(CASE WHEN f.SALE_HOUR  < 110000 THEN 1 -- am
        WHEN f.SALE_HOUR  >=110000 AND f.SALE_HOUR  < 140000 THEN 2 -- midday
        WHEN f.SALE_HOUR  >=140000 AND f.SALE_HOUR  < 160000 THEN 3 -- pm
        WHEN f.SALE_HOUR  >=160000 THEN 4 -- evening
        ELSE 0 
        END) AS DAY_PART
FROM APPBUS.AFT_POS_INTL_HDR_VW f
    INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 3
  INNER JOIN APPDWH.ADT_STORE org
      ON f.STORE_NUMBER = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('CA')
         AND org.AREA_DESCR = 'British Columbia 3'
GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.STORE_NUMBER
  ,f.BUSINESS_DATE
  ,f.SALE_HOUR)
  SELECT SQ.FSCL_YR_NUM
  , SQ.FSCL_QTR_IN_YR_NUM
  , SQ.DAY_PART
  , SUM(SQ.TRANS) AS TRANS
  , COUNT(UNIQUE(SQ.BUSINESS_DATE)) AS DAY_COUNT
  , COUNT(UNIQUE(SQ.STORE_NUMBER)) AS STORE_COUNT
  , COUNT(UNIQUE(SQ.BUSINESS_DATE))*COUNT(UNIQUE(SQ.STORE_NUMBER)) AS ACTIVE_STORE_DAY_COUNT
  , ROUND(SUM(SQ.TRANS)/(COUNT(UNIQUE(SQ.BUSINESS_DATE))*COUNT(UNIQUE(SQ.STORE_NUMBER))),0) AS COSD
  FROM SQ
  GROUP BY SQ.FSCL_YR_NUM
  , SQ.FSCL_QTR_IN_YR_NUM
  , SQ.DAY_PART
  ORDER BY SQ.DAY_PART
    
  
--Channel mix by store
--416

SELECT
  --ss.STORE_NUM
  --ss.DRIVE_THRU_IND
  ROUND(COUNT(CASE WHEN ss.DRIVE_THRU_IND = 1 THEN ss.DRIVE_THRU_IND END) / COUNT(CASE WHEN ss.DRIVE_THRU_IND BETWEEN 0 AND 1 THEN ss.DRIVE_THRU_IND END),3) AS DT_PCT
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,COUNT(DISTINCT tr.TRANS_ID) AS TTL_TRANS_CNT
  --,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) AS MOP_TRANS_CNT
  --,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) AS OTW_TRANS_CNT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) / COUNT(DISTINCT tr.TRANS_ID),4)*100 AS MOP_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END),4)*100 AS PEAK_MOP_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 AND ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 THEN tr.TRANS_ID END),4)*100 AS PM_MOP_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) / COUNT(DISTINCT tr.TRANS_ID),4)*100 AS OTW_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END),4)*100 AS PEAK_OTW_PCT
  ,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 AND ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 140000 AND 155959 THEN tr.TRANS_ID END),4)*100 AS PM_OTW_PCT
  
FROM APPCA.F_POS_HDR tr

INNER JOIN D_POS_HDR_TRANS_TYPE ty
  ON tr.POS_HDR_TRANS_TYPE_KEY = ty.POS_HDR_TRANS_TYPE_KEY
  
INNER JOIN APPCA.D_STORE_VERS ss
  ON ss.STORE_VERS_KEY = tr.STORE_VERS_KEY
  
INNER JOIN APPCA.D_CAL ca
  ON tr.BUS_DT = ca.CAL_DT

WHERE tr.CNTRY_CD = 'CA'
  AND ss.OWNR_TYPE_CD = 'CO'
  AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 3
  AND ss.AREA_DESCR = 'British Columbia 3'

GROUP BY
  --ss.STORE_NUM
  ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  --,ss.DRIVE_THRU_IND
  
 
--415
--SM Stability

SELECT
s.FSCL_PER_BEG_DT
--s.ORG_UNIT_NUM,
--s.STORE_NUM,
,ROUND(COUNT(CASE WHEN s.SM1YRSTABLE = 1 THEN s.SM1YRSTABLE END) / COUNT(CASE WHEN s.SM1YRSTABLE BETWEEN 0 AND 1 THEN s.SM1YRSTABLE END),3) AS SM1YRSTABLE_PCT
,ROUND(COUNT(CASE WHEN s.SM2YRSTABLE = 1 THEN s.SM2YRSTABLE END) / COUNT(CASE WHEN s.SM2YRSTABLE BETWEEN 0 AND 1 THEN s.SM2YRSTABLE END),3) AS SM2YRSTABLE_PCT

FROM LRIVERS.STOREMANAGERSTABILITY s

LEFT JOIN ADV_STORE str
    on s.STORE_NUM = str.STORE_NUM
    AND str.AREA_DESCR = 'British Columbia 3'
    AND str.OWNR_TYPE_CD IN ('CO')

/* get most recent rolling 12 report (table updates once per month) */
WHERE s.FSCL_PER_BEG_DT = (select max(FSCL_PER_BEG_DT) from LRIVERS.STOREMANAGERSTABILITY)

GROUP BY
s.FSCL_PER_BEG_DT
--s.ORG_UNIT_NUM,
--s.STORE_NUM,
--s.SM1YRSTABLE,
--s.SM2YRSTABLE