--416

SELECT
   ss.STORE_NUM
  ,ss.DRIVE_THRU_IND
  --,ty.ORD_MTHD_CD
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_PER_IN_YR_NUM
  ,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'CAFE' THEN tr.TRANS_ID END) AS CAFE_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'MOP' THEN tr.TRANS_ID END) AS MOP_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN ty.ORD_MTHD_CD = 'OTW' THEN tr.TRANS_ID END) AS OTW_TRANS_CNT
  ,COUNT(DISTINCT tr.TRANS_ID) AS TTL_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 1 THEN tr.TRANS_ID END) AS PEAK_CAFE_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 1 THEN tr.TRANS_ID END) AS PEAK_MOP_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.ORD_MTHD_CD = 1 THEN tr.TRANS_ID END) AS PEAK_OTW_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END) AS PEAK_TTL_TRANS_CNT

FROM APPCA.F_POS_HDR tr

INNER JOIN D_POS_HDR_TRANS_TYPE ty
  ON tr.POS_HDR_TRANS_TYPE_KEY = ty.POS_HDR_TRANS_TYPE_KEY
  
INNER JOIN APPCA.D_STORE_VERS ss
  ON ss.STORE_VERS_KEY = tr.STORE_VERS_KEY
  
INNER JOIN APPCA.D_CAL ca
  ON tr.BUS_DT = ca.CAL_DT

WHERE tr.CNTRY_CD = 'US'
  AND ss.OWNR_TYPE_CD = 'CO'
  AND ss.STORE_OPEN_DT < '29-JUN-15'  -- beginning of Q4FY15
  AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_PER_IN_YR_NUM = 5
  
HAVING COUNT(DISTINCT tr.TRANS_ID) > 1000

GROUP BY
   ss.STORE_NUM
  ,ss.DRIVE_THRU_IND
  --,ty.ORD_MTHD_CD
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_PER_IN_YR_NUM