/* Pulls comps by day part */

SELECT FISCAL_YEAR_NUMBER, DAY_PART_DESCRIPTION, DAY_PART_NAME,
   sum(SALES_AMT) AS sales_amt,   
   --sum(TRANS_CNT),
   sum(SALES_LY_AMT) AS sales_ly_amt
   --sum(TRANS_LY_CNT) 
FROM APPBUS.USR_CO_STORE_WEEK_HOUR_RPT

--GETTING ACTIVE STORE DAY COUNT BY DAY PART
WITH SQ AS 
(SELECT SUM(ACTIVE_STORE_DAY_CNT) AS DAY_COUNT, ca.FSCL_YR_NUM FROM APPBUS.DFT_INTL_STORE_DAY_VW f    
  INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM in (2018) AND ca.FSCL_PER_IN_YR_NUM IN (4,5,6)
  INNER JOIN APPDWH.DDM_RETAIL_ORG_STORE_DIST org
        ON f.STORE_NUMBER = org.STORE_NUM
        AND org.DIV_ORG_LVL_ID IN (3,6,106)  -- US CO stores
 GROUP BY ca.FSCL_YR_NUM)
SELECT SQ.DAY_COUNT, c.FISCAL_YEAR_NUMBER, 
    c.DAY_PART_DESCRIPTION, 
    c.DAY_PART_NAME,
   sum(c.TRANS_CNT) AS TRANS_COUNT,
   round(sum(c.TRANS_CNT)/SQ.DAY_COUNT,0) AS COSD
FROM SQ

INNER JOIN APPBUS.USR_CO_STORE_WEEK_HOUR_RPT c
  ON SQ.FSCL_YR_NUM = c.FISCAL_YEAR_NUMBER

INNER JOIN APPDWH.DDM_RETAIL_ORG_STORE_DIST org
  ON c.STORE_NUMBER = org.STORE_NUM
  AND org.DIV_ORG_LVL_ID IN (3,6,106)  -- US CO stores

WHERE c.DAY_PART_NAME IS NOT NULL

GROUP BY SQ.DAY_COUNT, c.FISCAL_YEAR_NUMBER, c.DAY_PART_DESCRIPTION, c.DAY_PART_NAME

