/* Pulls comps by day part */

SELECT  STORE_NUMBER, 
    FISCAL_YEAR_NUMBER, DAY_PART_DESCRIPTION, DAY_PART_NAME,
   sum(SALES_AMT) AS sales_amt,   
   --sum(TRANS_CNT),  
   sum(SALES_LY_AMT) AS sales_ly_amt
   --sum(TRANS_LY_CNT) 
FROM APPBUS.USR_CO_STORE_WEEK_HOUR_RPT
where  FISCAL_YEAR_NUMBER=2018 AND FISCAL_PERIOD_NUMBER IN (1,2,3)
group by STORE_NUMBER, FISCAL_YEAR_NUMBER, DAY_PART_DESCRIPTION, DAY_PART_NAME
