/* Pulls comps by day part */

SELECT FISCAL_YEAR_NUMBER, DAY_PART_DESCRIPTION, DAY_PART_NAME,
    --,STORE_NUMBER
   sum(SALES_AMT) AS sales_amt,   
   --sum(TRANS_CNT),  
   sum(SALES_LY_AMT) AS sales_ly_amt
   --sum(TRANS_LY_CNT) 
FROM APPBUS.USR_CO_STORE_WEEK_HOUR_RPT
where  FISCAL_YEAR_NUMBER=2018 AND FISCAL_PERIOD_NUMBER IN (4,5,6)
group by FISCAL_YEAR_NUMBER, DAY_PART_DESCRIPTION, DAY_PART_NAME
    --,STORE_NUMBER


--SELECT * FROM APPBUS.USR_CO_STORE_WEEK_HOUR_RPT