
/*customer transaction count by hour (and daypart indicator)*/
WITH SQ AS
(SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.SALE_HOUR 
  ,f.STORE_NUMBER
  ,f.BUSINESS_DATE
  ,SUM(f.CUTOMER_TRANSACTION_COUNT) AS "TRANS"
      ,(CASE WHEN f.SALE_HOUR  < 110000 THEN 1 -- am
        WHEN f.SALE_HOUR  >=110000 AND f.SALE_HOUR  < 140000 THEN 2 -- midday
        WHEN f.SALE_HOUR  >=140000 AND f.SALE_HOUR  < 160000 THEN 3 -- pm
        WHEN f.SALE_HOUR  >=160000 THEN 4 -- evening
        ELSE 0 
        END) AS DAY_PART
FROM APPBUS.AFT_POS_INTL_HDR_VW f
    INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 2
        AND f.COUNTRY_CODE = 'US'
  INNER JOIN APPDWH.ADT_STORE org
      ON f.STORE_NUMBER = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('US')
GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.STORE_NUMBER
  ,f.BUSINESS_DATE
  ,f.SALE_HOUR)
  SELECT SQ.FSCL_YR_NUM
  , SQ.FSCL_QTR_IN_YR_NUM
  , SQ.DAY_PART
  , SUM(SQ.TRANS) AS TRANS
  , COUNT(UNIQUE(SQ.BUSINESS_DATE)) AS DAY_COUNT
  , COUNT(UNIQUE(SQ.STORE_NUMBER)) AS STORE_COUNT
  , COUNT(UNIQUE(SQ.BUSINESS_DATE))*COUNT(UNIQUE(SQ.STORE_NUMBER)) AS ACTIVE_STORE_DAY_COUNT
  , ROUND(SUM(SQ.TRANS)/(COUNT(UNIQUE(SQ.BUSINESS_DATE))*COUNT(UNIQUE(SQ.STORE_NUMBER))),0) AS COSD
  FROM SQ
  GROUP BY SQ.FSCL_YR_NUM
  , SQ.FSCL_QTR_IN_YR_NUM
  , SQ.DAY_PART
  ORDER BY SQ.DAY_PART
