--411

SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_PER_IN_YR_NUM
  ,f.STORE_NUMBER
  , SUM(f.CUTOMER_TRANSACTION_COUNT) AS TRANS
  , COUNT(UNIQUE(f.BUSINESS_DATE)) AS DAY_COUNT
  , COUNT(UNIQUE(f.STORE_NUMBER)) AS STORE_COUNT
  , COUNT(UNIQUE(f.BUSINESS_DATE))*COUNT(UNIQUE(f.STORE_NUMBER)) AS ACTIVE_STORE_DAY_COUNT
  , ROUND(SUM(f.CUTOMER_TRANSACTION_COUNT)/(COUNT(UNIQUE(f.BUSINESS_DATE))*COUNT(UNIQUE(f.STORE_NUMBER))),0) AS COSD

FROM APPBUS.AFT_POS_INTL_HDR_VW f
  
  INNER JOIN APPDWH.ADT_CAL ca
      ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM = 2018 
        AND ca.FSCL_PER_IN_YR_NUM = 7
  
  INNER JOIN APPDWH.ADT_STORE org
      ON f.STORE_NUMBER = org.STORE_NUM
         AND org.OWNR_TYPE_CD IN ('CO')
         AND org.CNTRY_CD IN ('US')
GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_PER_IN_YR_NUM
  ,f.STORE_NUMBER
  