--SBP416

WITH SQ AS
      (SELECT
         POSH.GUID_ID
        ,STR.STORE_NUM
        ,ca.FSCL_YR_NUM
        ,ca.FSCL_PER_IN_YR_NUM
        ,COUNT(DISTINCT POSH.TRANS_ID) AS N_TRANS

      FROM APPCA.F_POS_HDR POSH
      LEFT OUTER JOIN APPCA.D_STORE_VERS STR
        ON POSH.STORE_VERS_KEY = STR.STORE_VERS_KEY
      INNER JOIN APPCA.D_CAL ca
        ON POSH.BUS_DT = ca.CAL_DT
      WHERE STR.OWNR_TYPE_CD = 'CO'
        AND STR.CNTRY_CD_2_DGT_ISO = 'US'
        AND POSH.GROSS_REV_LCL_AMT > 0
       AND ca.FSCL_YR_NUM = 2018 
       AND ca.FSCL_PER_IN_YR_NUM = 4
        
      GROUP BY
         POSH.GUID_ID
        ,STR.STORE_NUM
        ,ca.FSCL_YR_NUM
        ,ca.FSCL_PER_IN_YR_NUM
        ), SQ2 AS
(SELECT 
 SQ.STORE_NUM
,SQ.FSCL_YR_NUM
,SQ.FSCL_PER_IN_YR_NUM
,(CASE WHEN SQ.N_TRANS < 26 THEN 0
      WHEN SQ.N_TRANS >= 26 THEN 1
      END) AS HIGH_TRANS_CUST
,SQ.GUID_ID

FROM SQ

GROUP BY
 SQ.STORE_NUM
,SQ.FSCL_YR_NUM
,SQ.FSCL_PER_IN_YR_NUM
,SQ.N_TRANS
,SQ.GUID_ID)
SELECT 
 SQ2.STORE_NUM
,SQ2.FSCL_YR_NUM
,SQ2.FSCL_PER_IN_YR_NUM
,SQ2.HIGH_TRANS_CUST
,COUNT(GUID_ID) AS N_CUST
FROM SQ2
GROUP BY 
 SQ2.STORE_NUM
,SQ2.FSCL_YR_NUM
,SQ2.FSCL_PER_IN_YR_NUM
,SQ2.HIGH_TRANS_CUST