--/* CAW */
--/* % home store customers */

WITH SQ AS(
SELECT
   T3.STORE_NUM
  ,T3.FSCL_YR_NUM
  --,SUM(CASE WHEN T2.HOME_STORE = T3.STORE_NUM THEN 1 ELSE NULL END) AS HS_CUST_COUNT
  --,COUNT(DISTINCT T2.GUID_ID) AS ALL_CUST_COUNT
  ,ROUND(SUM(CASE WHEN T2.HOME_STORE = T3.STORE_NUM THEN 1 ELSE NULL END) / COUNT(DISTINCT T2.GUID_ID),4) AS HS_CUST_PCT
FROM(
    --LIST OF ALL ACTIVE STORES AND GUIDS WHO VISITED THOSE STORES DURING THE GIVEN TIME PERIOD
    SELECT
       STR.STORE_NUM
      ,ca.FSCL_YR_NUM
      ,POSH2.GUID_ID
    FROM APPCA.F_POS_HDR POSH2
    LEFT OUTER JOIN APPCA.D_STORE_VERS STR
      ON POSH2.STORE_VERS_KEY = STR.STORE_VERS_KEY
    INNER JOIN APPCA.D_CAL ca
      ON POSH2.BUS_DT = ca.CAL_DT
    WHERE STR.OWNR_TYPE_CD = 'CO'
      AND STR.CNTRY_CD_2_DGT_ISO = 'US'
      AND POSH2.GROSS_REV_LCL_AMT > 0
       AND ca.FSCL_YR_NUM IN (2017,2018)
       AND ca.FSCL_WK_IN_YR_NUM IN (30,31,32,33)
           AND STR.STORE_NUM IN (101,104)
    GROUP BY
       STR.STORE_NUM
      ,ca.FSCL_YR_NUM
      ,POSH2.GUID_ID
    ) T3
  --JOINING LIST OF GUIDS WHO WERE ACTIVE, THEIR HOMESTORE, TOTAL TRANSACTIONS AND SPEND AT ALL STORES
  INNER JOIN (
    SELECT
       T1.GUID_ID
      ,T1.FSCL_YR_NUM
      ,SUM(CASE WHEN T1.RNK_HS = 1 AND T1.N_TRANS>=3 
         THEN T1.STORE_NUM 
         ELSE NULL 
       END) AS HOME_STORE
      ,SUM(CASE WHEN T1.RNK_HS = 1 AND T1.N_TRANS>=3 
         THEN T1.N_TRANS 
         ELSE NULL 
       END) AS HOME_STORE_VISITS
      ,SUM(CASE WHEN T1.RNK_HS = 1 AND T1.N_TRANS>=3 
         THEN T1.TOT_SPEND 
         ELSE NULL 
       END) AS HOME_STORE_SPEND
      ,SUM(T1.N_TRANS) AS ALL_STORES_VISITS
      ,SUM(T1.TOT_SPEND) AS ALL_STORES_SPEND
    FROM(
      --INNER QUERY - ALL GUIDS, STORES THEY VISITED, # TRANSACTIONS AT THOSE STORES AND TOTAL SPEND AT THOSE STORES
      SELECT
         POSH.GUID_ID
        ,STR.STORE_NUM
        ,ca.FSCL_YR_NUM
        ,COUNT(DISTINCT POSH.TRANS_ID) AS N_TRANS
        ,SUM(POSH.GROSS_REV_LCL_AMT) AS TOT_SPEND
        --this ranks each store that the guid has visited by the number of transactions and spend
        ,RANK() OVER(PARTITION BY POSH.GUID_ID, ca.FSCL_YR_NUM 
                  ORDER BY -COUNT(DISTINCT POSH.TRANS_ID), 
                           -SUM(POSH.GROSS_REV_LCL_AMT)
                  ) 
         AS RNK_HS
      FROM APPCA.F_POS_HDR POSH
      LEFT OUTER JOIN APPCA.D_STORE_VERS STR
        ON POSH.STORE_VERS_KEY = STR.STORE_VERS_KEY
      INNER JOIN APPCA.D_CAL ca
        ON POSH.BUS_DT = ca.CAL_DT
      WHERE STR.OWNR_TYPE_CD = 'CO'
        AND STR.CNTRY_CD_2_DGT_ISO = 'US'
        AND POSH.GROSS_REV_LCL_AMT > 0
       AND ca.FSCL_YR_NUM IN (2017,2018)
       AND ca.FSCL_WK_IN_YR_NUM IN (30,31,32,33)
       AND STR.STORE_NUM IN (101,104)
        
      GROUP BY
         POSH.GUID_ID
        ,STR.STORE_NUM
        ,ca.FSCL_YR_NUM

    ) T1 --THIS IS THE LIST OF GUIDS AND THEIR HOMESTORE,SPEND ETC
    GROUP BY
       T1.GUID_ID
      ,T1.FSCL_YR_NUM

  ) T2 --THIS IS THE LIST OF ALL STORES AND THEIR CUSTOMERS
ON T2.GUID_ID = T3.GUID_ID
  AND T2.FSCL_YR_NUM = T3.FSCL_YR_NUM

WHERE T2.GUID_ID IS NOT NULL 
  AND T3.GUID_ID IS NOT NULL 
  AND T2.GUID_ID !='0' 
  AND T3.GUID_ID !='0' 

GROUP BY
   T3.STORE_NUM
  ,T3.FSCL_YR_NUM
  
  ORDER BY
   T3.FSCL_YR_NUM ASC
   ,T3.STORE_NUM DESC), SQ2 AS(
SELECT
    SQ.FSCL_YR_NUM
    ,SQ.STORE_NUM
    ,SQ.HS_CUST_PCT
    ,SQ.HS_CUST_PCT - lag(SQ.HS_CUST_PCT) over(order by SQ.STORE_NUM, SQ.FSCL_YR_NUM) AS HS_CUST_PCT_YOY_DELTA
FROM SQ
ORDER BY
    SQ.FSCL_YR_NUM DESC
    ,SQ.STORE_NUM DESC) 
SELECT 
    SQ2.STORE_NUM
    ,SQ2.HS_CUST_PCT
    ,SQ2.HS_CUST_PCT_YOY_DELTA
FROM SQ2
    WHERE SQ2.FSCL_YR_NUM = 2018
