SELECT t.GUID_USER_ID
,t.GENDER
,t.COMBINED_AGE
,t.EDUCATION_MODEL
,t.MARITAL_STATUS
,t.OCCUPATION_GROUP_V2
,t.EST_HOUSEHOLD_INCOME_V5
--,t.RURAL_URBAN_COUNTY_CODE
FROM DEPT_RET_AN.CUSTOMER_TEST t

INNER JOIN APPCA.F_SVC_FIN_TRANS a
  ON t.GUID_USER_ID = a.GUID_ID

INNER JOIN APPCA.D_CAL b 
  ON a.BUS_DT = b.CAL_DT

WHERE t.SBUX_MATCH_LEVEL IN ('IND')
  AND b.FSCL_YR_NUM = 2018 and b.FSCL_PER_IN_YR_NUM = 3


