SELECT DISTINCT
   STORE_NUMBER, DAY_OF_WEEK_NUMBER, HRS_TYPE_CD, 
   HOLIDAY_CD, BUSINESS_OPEN_TIME, BUSINESS_CLOSE_TIME, 
   --STAFF_START_TIME, STAFF_END_TIME, OPEN_STAFF_COUNT, 
   --CLOSE_STAFF_COUNT, 
   OPEN_24_HR_IND, BUSINESS_OPEN_CD, 
   EFFECTIVE_DATE, EXPIRATION_DATE, REC_STAT_CD
FROM APPBUS.SDT_LOC_MSTR_HRS_VW
    WHERE HOLIDAY_CD IS NULL
    --and DAY_OF_WEEK_NUMBER = 7
    AND HRS_TYPE_CD = 'P' AND effective_date is NOT NULL
ORDER BY effective_date ASC
;
