/* Pulls hours of operation at the store level */

SELECT STORE_NUM, DAY_OF_WK_NUM, PERM_BUS_OPEN_TM, PERM_BUS_CLOSE_TM, PERM_OPEN_24_HR_IND from APPDWH.ADT_STORE_HRS
ORDER BY STORE_NUM, DAY_OF_WK_NUM