SELECT
   sr.STORE_NUM
  ,st.DIST_NUM
  ,st.DIST_DESCR
  ,st.AREA_NUM
  ,st.AREA_DESCR
  ,st.RGN_NUM
  ,st.RGN_DESCR
  ,seg.LS_SEGMENT 
  --,h.SUBSEGMENT AS LICENSEE_SUBSEGMENT
  ,h.LICENSEE_PARENT_NAME AS ls_parent
  ,ca.FSCL_YR_NUM
  /*
  ,SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END) AS Q2_2_TB_COUNT
  ,SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END) AS Q2_2_TOTAL_RSPNS
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END)) OVER(PARTITION BY seg.LS_SEGMENT) AS Q2_2_SEG_TB_CNT
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)) OVER(PARTITION BY seg.LS_SEGMENT) AS Q2_2_SEG_TOTAL_RSPNS
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END)) OVER(PARTITION BY h.SUBSEGMENT) AS Q2_2_SUBSEG_TB_CNT
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)) OVER(PARTITION BY h.SUBSEGMENT) AS Q2_2_SUBSEG_TOTAL_RSPNS
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END)) OVER(PARTITION BY st.DIST_NUM) AS Q2_2_DIST_TB_CNT
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)) OVER(PARTITION BY st.DIST_NUM) AS Q2_2_DIST_TOTAL_RSPNS
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END)) OVER(PARTITION BY st.AREA_NUM) AS Q2_2_AREA_TB_CNT
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)) OVER(PARTITION BY st.AREA_NUM) AS Q2_2_AREA_TOTAL_RSPNS
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END)) OVER(PARTITION BY st.RGN_NUM) AS Q2_2_RGN_TB_CNT
  ,SUM(SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END)) OVER(PARTITION BY st.RGN_NUM) AS Q2_2_RGN_TOTAL_RSPNS
  */
  -- Total valid response counts by question
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_1' THEN sr.QSTN_ID END) AS Q2_1_Response_Total
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN sr.QSTN_ID END) AS Q2_2_Response_Total
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_3' THEN sr.QSTN_ID END) AS Q2_3_Response_Total
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_4' THEN sr.QSTN_ID END) AS Q2_4_Response_Total
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_5' THEN sr.QSTN_ID END) AS Q2_5_Response_Total
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_6' THEN sr.QSTN_ID END) AS Q2_6_Response_Total
  ,COUNT(CASE WHEN sr.QSTN_ID = 'Q2_7' THEN sr.QSTN_ID END) AS Q2_7_Response_Total
  
  -- Total top box responses
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_1' THEN 1 ELSE 0 END) AS Q2_1_TB_Cnt
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END) AS Q2_2_TB_Cnt
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_3' THEN 1 ELSE 0 END) AS Q2_3_TB_Cnt
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_4' THEN 1 ELSE 0 END) AS Q2_4_TB_Cnt
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_5' THEN 1 ELSE 0 END) AS Q2_5_TB_Cnt
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_6' THEN 1 ELSE 0 END) AS Q2_6_TB_Cnt
  ,SUM(CASE WHEN sr.RSPNS_ID = '7' AND sr.QSTN_ID = 'Q2_7' THEN 1 ELSE 0 END) AS Q2_7_TB_Cnt

FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

INNER JOIN APPCA.D_CAL ca
  ON TRUNC(sr.TRANS_DTM) = ca.CAL_DT
  
INNER JOIN APPCA.D_STORE_VERS st
  ON st.STORE_NUM = sr.STORE_NUM
    AND st.CURRENT_FLG = 'Y'

/* Table from Cambridge that has subsegment info for all licencee stores. */
LEFT JOIN DEPT_CUST_INS.TN_LS_HEIRARCHY_8_15_17 h
  ON sr.STORE_NUM = h.STORE_NUMBER

/* Table from Dina Updegraff [Segment and SubSegment Codes.xlsx] that has Segment roll-up map. */
LEFT JOIN DEPT_CUST_INS.TN_LS_SEG_MAP seg
  ON h.SUBSEGMENT = seg.SUBSEGMENT

WHERE sr.QSTN_ID IN ('Q2_1','Q2_2','Q2_3','Q2_4','Q2_5','Q2_6','Q2_7')
  --sr.QSTN_ID = 'Q2_2'
  AND sr.RSPNS_ID <> '9'
  AND TRUNC(sr.TRANS_DTM) >= '30-SEP-16'
  AND st.OWNR_TYPE_CD = 'LS'
  AND st.CNTRY_CD_2_DGT_ISO = 'US'
  AND (ca.FSCL_YR_NUM = 2017 OR ca.FSCL_YR_NUM = 2018)
  AND ca.FSCL_PER_IN_YR_NUM BETWEEN 1 AND 2 --rolling 2 months
  
GROUP BY
   sr.STORE_NUM
  ,st.DIST_NUM
  ,st.DIST_DESCR
  ,st.AREA_NUM
  ,st.AREA_DESCR
  ,st.RGN_NUM
  ,st.RGN_DESCR
  ,seg.LS_SEGMENT
  --,h.SUBSEGMENT
  ,h.LICENSEE_PARENT_NAME
  ,ca.FSCL_YR_NUM
;

