SELECT
--   ca.FSCL_PER_IN_YR_NUM
--  ,ca.FSCL_PER_IN_YR_CD
   sr.STORE_NUM
  ,st.DIST_NUM
  ,st.DIST_DESCR
  ,st.AREA_NUM
  ,st.AREA_DESCR
  ,st.RGN_NUM
  ,st.RGN_DESCR
  ,seg.LS_SEGMENT AS LICENSEE_SEGMENT
  ,h.SUBSEGMENT AS LICENSEE_SUBSEGMENT
  ,h.LICENSEE_PARENT_NAME
  ,CASE WHEN ca.FSCL_PER_IN_YR_NUM IN (2,3,4) THEN 'aStart' ELSE 'zEnd' END AS PERIOD
  ,SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' AND sr.RSPNS_ID = '7' THEN 1 ELSE 0 END) AS Q2_2_TB_COUNT
  ,SUM(CASE WHEN sr.QSTN_ID = 'Q2_2' THEN 1 ELSE 0 END) AS Q2_2_TOTAL_RSPNS
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

INNER JOIN APPCA.D_CAL ca
  ON TRUNC(sr.TRANS_DTM) = ca.CAL_DT
  
INNER JOIN APPCA.D_STORE_VERS st
  ON st.STORE_NUM = sr.STORE_NUM
    AND st.CURRENT_FLG = 'Y'

/* Table from Cambridge that has subsegment info for all licencee stores. */
LEFT JOIN DEPT_CUST_INS.TN_LS_HEIRARCHY_8_15_17 h
  ON sr.STORE_NUM = h.STORE_NUMBER

/* Table from Dina Updegraff [Segment and SubSegment Codes.xlsx] that has Segment roll-up map. */
LEFT JOIN DEPT_CUST_INS.TN_LS_SEG_MAP seg
  ON h.SUBSEGMENT = seg.SUBSEGMENT

WHERE --sr.QSTN_ID IN ('Q2_1','Q2_2','Q2_3','Q2_4','Q2_5','Q2_6','Q2_7')
  sr.QSTN_ID = 'Q2_2'
  AND sr.RSPNS_ID <> '9'
  AND TRUNC(sr.TRANS_DTM) >= '19-SEP-16'
  AND st.OWNR_TYPE_CD = 'LS'
  AND st.CNTRY_CD_2_DGT_ISO = 'US'
  AND ca.FSCL_YR_NUM = 2017
  AND ca.FSCL_PER_IN_YR_NUM IN (2,3,4,9,10,11)
  
GROUP BY
--   ca.FSCL_PER_IN_YR_NUM
--  ,ca.FSCL_PER_IN_YR_CD
   sr.STORE_NUM
  ,st.DIST_NUM
  ,st.DIST_DESCR
  ,st.AREA_NUM
  ,st.AREA_DESCR
  ,st.RGN_NUM
  ,st.RGN_DESCR
  ,seg.LS_SEGMENT
  ,h.SUBSEGMENT
  ,h.LICENSEE_PARENT_NAME
  ,CASE WHEN ca.FSCL_PER_IN_YR_NUM IN (2,3,4) THEN 'aStart' ELSE 'zEnd' END
;