/*For monthly LS mapping*/

SELECT * FROM APPEXT.SVC_MRCHT_LS_MAP m
  --WHERE m.SVC_MRCHT_ID = 97076400001
  --ORDER BY m.ALT_MID_ID desc
  --DELETE FROM APPEXT.SVC_MRCHT_LS_MAP m
  --WHERE TRUNC(m.UPDT_DT) >= '01-NOV-17';