/* Pulls the ALTMIDs associated with MIDs */
/* For Cambridge requests */

/* Counts SR transactions associated with MID/ALTMID combinations */
SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, COUNT(*) FROM APPCA.F_CARD ac
    WHERE ac.ALT_MRCHT_ID IN (51726) 
    --AND ac.MRCHT_ID IN (97039100009) 
    AND ac.TRANS_DT > '05-feb-18' 
    GROUP BY ac.MRCHT_ID, ac.ALT_MRCHT_ID

/* Counts SR transactions associated with MID/ALTMID combinations */
SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, COUNT(*) FROM APPCA.F_CARD ac
    WHERE ( (ac.ALT_MRCHT_ID IN (40167) AND ac.MRCHT_ID IN (97039100009 ))
      OR (ac.ALT_MRCHT_ID IN (48053,49410))
      OR (ac.ALT_MRCHT_ID IN (49913) AND ac.MRCHT_ID IN (97056000003)) )
    AND ac.TRANS_DT > '13-feb-18' 
    GROUP BY ac.MRCHT_ID, ac.ALT_MRCHT_ID


/* Laste date received SR transactions associated with MID/ALTMID combinations */
SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, TRUNC(ac.TRANS_DT) FROM APPCA.F_CARD ac
    WHERE 
    --ac.MRCHT_ID IN (97056000003)
    --AND 
    ac.ALT_MRCHT_ID IN (48691) 
        --AND ac.TRANS_DT > '03-JUN-17' 
    ORDER BY ac.ALT_MRCHT_ID, TRUNC(ac.TRANS_DT) DESC 

/*SR transactions per month associated with MID/ALTMID combinations */
SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, COUNT(*) AS TRANS FROM APPCA.F_CARD ac
    WHERE ac.ALT_MRCHT_ID IN (75621) 
    AND ac.MRCHT_ID IN (97025906215,97231300005)
    AND (ac.TRANS_DT >= '30-OCT-17' AND ac.TRANS_DT <= '26-NOV-17')
    --AND (ac.TRANS_DT >= '27-NOV-17' AND ac.TRANS_DT <= '31-DEC-17')
    --AND (ac.TRANS_DT >= '01-JAN-18' AND ac.TRANS_DT <= '28-JAN-18')
GROUP BY  ac.MRCHT_ID, ac.ALT_MRCHT_ID


/* SURVEY COUNTS */
SELECT
   sr.STORE_NUM AS SBUX_STORE_NUM
  ,COUNT(sr.CASE_ID) AS TOTAL_RSPNS_CNT
  ,MIN(TRUNC(sr.TRANS_DTM)) AS EARLIEST_RSPNS_DT
  ,MAX(TRUNC(sr.TRANS_DTM)) AS LATEST_RSPNS_DT
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr
WHERE sr.QSTN_ID = 'Q1'
  AND sr.STORE_NUM IN (29954,47123)
  --AND TRUNC(sr.TRANS_DTM) >= '01-JAN-2018'
GROUP BY
   sr.STORE_NUM


/* SURVEY COUNTS DATA TABLE */
SELECT * FROM APPOTHER.AFT_CV_SRVY_RSPNS sr
WHERE sr.STORE_NUM IN (76622) 


/*
SELECT MRCHT_ID, ALT_MRCHT_ID, TRANS_DT
FROM
(
  SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, ac.TRANS_DT,
    row_number() over(partition by ac.MRCHT_ID 
                        order by ac.TRANS_DT desc) seq
  FROM APPCA.F_CARD ac
  WHERE ac.MRCHT_ID IN (97270200009,97270300007,97267500007)
  AND ac.ALT_MRCHT_ID > 0
) 
WHERE seq = 1
*/

