/* Pulls the ALTMIDs associated with MIDs */
/* For Cambridge requests */

/* Counts SR transactions associated with MID/ALTMID combinations */
SELECT ac.STORE_NUM, ac.MRCHT_ID, ac.ALT_MRCHT_ID, COUNT(*) FROM APPCA.F_CARD ac
    WHERE ac.ALT_MRCHT_ID IN (28721) 
    --AND ac.MRCHT_ID IN (97056000003)
    AND ac.TRANS_DT > '28-DEC-17' 
    GROUP BY ac.STORE_NUM, ac.MRCHT_ID, ac.ALT_MRCHT_ID

/* Counts SR transactions associated with MID/ALTMID combinations */
SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, COUNT(*) FROM APPCA.F_CARD ac
    WHERE ( (ac.ALT_MRCHT_ID IN (29954) AND ac.MRCHT_ID IN (97056000003 ))
      OR (ac.ALT_MRCHT_ID IN (1380) AND ac.MRCHT_ID IN (97056000003))
      OR (ac.ALT_MRCHT_ID IN (1155) AND ac.MRCHT_ID IN (97056000003))
      OR (ac.ALT_MRCHT_ID IN (1559) AND ac.MRCHT_ID IN (97056000003))
      OR (ac.ALT_MRCHT_ID IN (49913) AND ac.MRCHT_ID IN (97056000003))
      OR (ac.ALT_MRCHT_ID IN (1562) AND ac.MRCHT_ID IN (97056000003))
      OR (ac.ALT_MRCHT_ID IN (1151) AND ac.MRCHT_ID IN (97056000003))
      OR (ac.ALT_MRCHT_ID IN (1090) AND ac.MRCHT_ID IN (97056000003)) )
    AND ac.TRANS_DT > '07-DEC-17' 
    GROUP BY ac.MRCHT_ID, ac.ALT_MRCHT_ID


/* Laste date received SR transactions associated with MID/ALTMID combinations */
SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, TRUNC(ac.TRANS_DT) FROM APPCA.F_CARD ac
    WHERE 
    ac.ALT_MRCHT_ID IN (47128) AND ac.MRCHT_ID IN (97053200002)
        --AND ac.TRANS_DT > '03-JUN-17' 
    ORDER BY TRUNC(ac.TRANS_DT) DESC 

/* SURVEY COUNTS */
SELECT
   sr.STORE_NUM AS SBUX_STORE_NUM
  ,COUNT(sr.CASE_ID) AS TOTAL_RSPNS_CNT
  --,COUNT(CASE WHEN TRUNC(sr.TRANS_DTM) >= '27-DEC-17' THEN 1 END) AS FISCAL_DEC_RSPNS_CNT  -- only if it's the 1st day of the fiscal month --UPDATE NAME
  ,MIN(TRUNC(sr.TRANS_DTM)) AS EARLIEST_RSPNS_DT
  ,MAX(TRUNC(sr.TRANS_DTM)) AS LATEST_RSPNS_DT
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr
WHERE sr.QSTN_ID = 'Q1'
  AND sr.STORE_NUM IN (47128)
GROUP BY
   sr.STORE_NUM

/* SURVEY COUNTS DATA TABLE */
SELECT * FROM APPOTHER.AFT_CV_SRVY_RSPNS sr
WHERE sr.STORE_NUM IN (47128) 


/*
SELECT MRCHT_ID, ALT_MRCHT_ID, TRANS_DT
FROM
(
  SELECT ac.MRCHT_ID, ac.ALT_MRCHT_ID, ac.TRANS_DT,
    row_number() over(partition by ac.MRCHT_ID 
                        order by ac.TRANS_DT desc) seq
  FROM APPCA.F_CARD ac
  WHERE ac.MRCHT_ID IN (97270200009,97270300007,97267500007)
  AND ac.ALT_MRCHT_ID > 0
) 
WHERE seq = 1
*/


SELECT * FROM APPOTHER.AFT_CV_SRVY_RSPNS sr
WHERE sr.STORE_NUM = 49913