/* MOP Percent by Store */
/* export as "MOP_percent_by_store.csv" */

SELECT
   ss.STORE_NUM
  --,ss.STORE_OPEN_DT
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  --,COUNT(DISTINCT CASE WHEN ty.MOBILE_ORD_PAY_IND = 1 THEN tr.TRANS_ID END) AS MOP_TRANS_CNT
  --,COUNT(DISTINCT tr.TRANS_ID) AS TTL_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.MOBILE_ORD_PAY_IND = 1 THEN tr.TRANS_ID END) AS PEAK_MOP_TRANS_CNT
  ,COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END) AS PEAK_TTL_TRANS_CNT
  --,ROUND(COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 AND ty.MOBILE_ORD_PAY_IND = 1 THEN tr.TRANS_ID END) / COUNT(DISTINCT CASE WHEN tr.TRANS_END_TM_KEY BETWEEN 70000 AND 95959 THEN tr.TRANS_ID END),4)*100 AS PEAK_MOP_PCT
FROM APPCA.F_POS_HDR tr

INNER JOIN D_POS_HDR_TRANS_TYPE ty
  ON tr.POS_HDR_TRANS_TYPE_KEY = ty.POS_HDR_TRANS_TYPE_KEY
  
INNER JOIN APPCA.D_STORE_VERS ss
  ON ss.STORE_VERS_KEY = tr.STORE_VERS_KEY
  
INNER JOIN APPCA.D_CAL ca
  ON tr.BUS_DT = ca.CAL_DT

WHERE tr.CNTRY_CD = 'US'
  AND ss.OWNR_TYPE_CD = 'CO'
  AND ss.DRIVE_THRU_IND = 0
  AND ss.STORE_OPEN_DT < '29-JUN-15'  -- beginning of Q4FY15
  AND ca.FSCL_YR_NUM >= 2017
  --AND ca.FSCL_QTR_IN_YR_NUM = 1
  
--HAVING COUNT(DISTINCT tr.TRANS_ID) > 1000

GROUP BY
   ss.STORE_NUM
  --,ss.STORE_OPEN_DT
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
;