--415
--Partner JOB ID
WITH prtnr AS 
(SELECT SAP_PRTNR_ID AS PRTNR_ID
      --,ORIG_HIRE_DT
      --,MOST_RECENT_HIRE_DT
      --,SEPARATION_DT
      --,SNAPSHOT_DT
      ,EMP_STAT_CD
      ,ROW_NUMBER() OVER (PARTITION BY SAP_PRTNR_ID ORDER BY EFF_FROM_DT DESC) AS mostrec
    FROM D_PRTNR_VERS
    WHERE EMP_STAT_CD IN ('Separated','Active')
      AND SNAPSHOT_DT = (select max(SNAPSHOT_DT) from D_PRTNR_VERS)
      --AND PRTNR_CNTRY_CD = 'US'
      --AND SAP_PRTNR_ID IN (1911743,2034275,2184173,1601272,2026175,1551015,2109245,2021524,2350486)
 ) SELECT 
      prtnr.PRTNR_ID
      --,prtnr.ORIG_HIRE_DT
      --,prtnr.MOST_RECENT_HIRE_DT
      --,prtnr.SEPARATION_DT
      --,prtnr.SNAPSHOT_DT
      ,prtnr.EMP_STAT_CD
      ,gls.JOB_ID
      ,gls.CNTRY_CD

FROM prtnr

INNER JOIN (
  SELECT * FROM (
    SELECT PRTNR_NUM, STORE_NUM, JOB_ID, CNTRY_CD,
    ROW_NUMBER() OVER (PARTITION BY PRTNR_NUM ORDER BY END_DTM DESC) AS mostrec
    FROM APPDWH.AFT_GLS_PRTNR_TMCARD@SBP411  
    WHERE BUS_DT BETWEEN '01-MAR-18' AND '02-JUL-18'
      AND CNTRY_CD IN ('US','CA')
      --AND JOB_ID IN (50000362,50000358,50000117)
    ) WHERE mostrec = 1
  ) gls 
  
ON prtnr.PRTNR_ID = gls.PRTNR_NUM
WHERE prtnr.mostrec = 1








--415 (PDW)
--Pulls partners' job id

select a.SAP_PRTNR_ID, a.EMP_STAT_CD, c.JOB_ID, c.JOB_NM, a.WORK_CNTRY_CD from APPPDW.DDT_PRTNR a

join APPPDW.DFT_RELATIONSHIPS b
on a.SNAPSHOT_DT = b.SNAPSHOT_DT
and a.PRTNR_VERS_KEY = b.PRTNR_VERS_KEY

join APPPDW.DDV_POSN_JOB c
on a.SNAPSHOT_DT = c.SNAPSHOT_DT
and b.POSN_JOB_VERS_KEY = c.POSN_JOB_VERS_KEY

where a.SNAPSHOT_DT = (select max(SNAPSHOT_DT) from APPPDW.DDT_PRTNR)
and b.SNAPSHOT_DT = (select max(SNAPSHOT_DT) from APPPDW.DFT_RELATIONSHIPS)
and c.SNAPSHOT_DT = (select max(SNAPSHOT_DT) from APPPDW.DDV_POSN_JOB)
and a.EFF_TO_DT = (select max(EFF_TO_DT) from APPPDW.DDT_PRTNR)
and b.EFF_TO_DT = (select max(EFF_TO_DT) from APPPDW.DFT_RELATIONSHIPS)
and c.EFF_TO_DT = (select max(EFF_TO_DT) from APPPDW.DDV_POSN_JOB)
and a.WORK_CNTRY_CD IN ('US','CA')
--and a.SAP_PRTNR_ID IN ('01147421')
order by a.SAP_PRTNR_ID
