WITH prtnr AS 
(SELECT SAP_PRTNR_ID AS PRTNR_ID
      --,ORIG_HIRE_DT
      --,MOST_RECENT_HIRE_DT
      --,SEPARATION_DT
      --,SNAPSHOT_DT
      ,EMP_STAT_CD
      ,ROW_NUMBER() OVER (PARTITION BY SAP_PRTNR_ID ORDER BY EFF_FROM_DT DESC) AS mostrec
    FROM D_PRTNR_VERS
    WHERE EMP_STAT_CD IN ('Separated','Active')
      AND SNAPSHOT_DT = (select max(SNAPSHOT_DT) from D_PRTNR_VERS)
      --AND PRTNR_CNTRY_CD = 'US'
      --AND SAP_PRTNR_ID IN (1911743,2034275,2184173,1601272,2026175,1551015,2109245,2021524,2350486)
 ) SELECT 
      prtnr.PRTNR_ID
      --,prtnr.ORIG_HIRE_DT
      --,prtnr.MOST_RECENT_HIRE_DT
      --,prtnr.SEPARATION_DT
      --,prtnr.SNAPSHOT_DT
      ,prtnr.EMP_STAT_CD
      ,gls.JOB_ID
      ,gls.CNTRY_CD

FROM prtnr

INNER JOIN (
  SELECT * FROM (
    SELECT PRTNR_NUM, JOB_ID, CNTRY_CD,
    ROW_NUMBER() OVER (PARTITION BY PRTNR_NUM ORDER BY END_DTM DESC) AS mostrec
    FROM APPDWH.AFT_GLS_PRTNR_TMCARD@SBP411  
    WHERE CNTRY_CD = 'US'
      AND BUS_DT BETWEEN '10-AUG-03' AND '10-DEC-03'
      AND JOB_ID IN (50000362,50000358,50000117)
    ) WHERE mostrec = 1
  ) gls 
  
ON prtnr.PRTNR_ID = gls.PRTNR_NUM
WHERE prtnr.mostrec = 1


/*
WITH SQ AS (SELECT SAP_PRTNR_ID AS PRTNR_ID
      ,ORIG_HIRE_DT
      ,MOST_RECENT_HIRE_DT
      ,SEPARATION_DT
      ,SNAPSHOT_DT
      ,EMP_STAT_CD
      ,ROW_NUMBER() OVER (PARTITION BY SAP_PRTNR_ID ORDER BY EFF_FROM_DT DESC) AS mostrec
    FROM D_PRTNR_VERS
    WHERE EMP_STAT_CD IN ('Separated','Active')
      AND SNAPSHOT_DT = '26-FEB-2018'
      AND PRTNR_CNTRY_CD = 'US'
) SELECT * FROM SQ
WHERE mostrec = 1

--select * from D_PRTNR_VERS
*/


WITH SQ AS (
SELECT SAP_PRTNR_ID AS PRTNR_ID
      ,ORIG_HIRE_DT
      ,MOST_RECENT_HIRE_DT
      ,SEPARATION_DT
      ,SNAPSHOT_DT
      ,EMP_STAT_CD
      ,ROW_NUMBER() OVER (PARTITION BY SAP_PRTNR_ID ORDER BY EFF_FROM_DT DESC) AS mostrec
    FROM D_PRTNR_VERS
    WHERE SAP_PRTNR_ID = '01147421'
    --EMP_STAT_CD IN ('Separated','Active')
      --AND SNAPSHOT_DT = '26-FEB-2018'
) SELECT * FROM SQ
WHERE mostrec = 1




WITH prtnr AS 
(SELECT SAP_PRTNR_ID AS PRTNR_ID
      ,ORIG_HIRE_DT
      ,MOST_RECENT_HIRE_DT
      ,SEPARATION_DT
      ,SNAPSHOT_DT
      ,EMP_STAT_CD
      ,ROW_NUMBER() OVER (PARTITION BY SAP_PRTNR_ID ORDER BY EFF_FROM_DT DESC) AS mostrec
    FROM D_PRTNR_VERS
    WHERE EMP_STAT_CD IN ('Separated','Active')
      AND SNAPSHOT_DT = '26-FEB-2018'
      AND PRTNR_CNTRY_CD = 'US'
      --AND SAP_PRTNR_ID IN (1911743,2034275,2184173,1601272,2026175,1551015,2109245,2021524,2350486)
 ) SELECT 
      prtnr.PRTNR_ID
      ,prtnr.ORIG_HIRE_DT
      ,prtnr.MOST_RECENT_HIRE_DT
      ,prtnr.SEPARATION_DT
      ,prtnr.SNAPSHOT_DT
      ,prtnr.EMP_STAT_CD
      ,gls.JOB_ID

FROM prtnr













select ORIG_HIRE_DT
      ,MOST_RECENT_HIRE_DT
      ,SEPARATION_DT
      ,SNAPSHOT_DT
      ,EMP_STAT_CD from D_PRTNR_VERS
WHERE SAP_PRTNR_ID = '01147421'
ORDER BY SNAPSHOT_DT ASC


    SELECT PRTNR_NUM, JOB_ID, END_DTM
    --ROW_NUMBER() OVER (PARTITION BY PRTNR_NUM ORDER BY END_DTM DESC) AS mostrec
    FROM APPDWH.AFT_GLS_PRTNR_TMCARD@SBP411  
    WHERE CNTRY_CD = 'US'
      AND BUS_DT BETWEEN '10-AUG-03' AND '10-DEC-03' --one week prior to launch of Pulse
      AND PRTNR_NUM = '01147421'
    order by END_DTM ASC
    
    SELECT * FROM DFT_SAP_EVENTS
