--This query joins CE with Store, POS and ITEM tables
--This gives the complete ability to filter by store chars, item numbers, category, number of items in basket, time of purchase etc.

SELECT S.CASE_ID,
  S.GUID_USER_ID,
  S.RSPNS_DT,
  S.TRANS_DTM,
  S.STORE_NUM, 
  S.RGSTR_NUM, 
  S.TRANS_ID,
  AVG(CASE WHEN S.QSTN_ID = 'Q1' THEN RSPNS_ID END) AS Q1,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_1' THEN RSPNS_ID END) AS Q2_1,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_2' THEN RSPNS_ID END) AS Q2_2,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_3' THEN RSPNS_ID END) AS Q2_3,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_4' THEN RSPNS_ID END) AS Q2_4,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_5' THEN RSPNS_ID END) AS Q2_5,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_6' THEN RSPNS_ID END) AS Q2_6,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_7' THEN RSPNS_ID END) AS Q2_7,
  AVG(CASE WHEN S.QSTN_ID = 'Q2_8' THEN RSPNS_ID END) AS Q2_8,
  --Weights for surveys before Aug 2015
  AVG(COALESCE(W.WEIGHT_RT,1.0)) AS WT,
  SUBSTR(TRIM(TO_CHAR(POS.TRANS_END_TM_KEY, '000000')),1,2) AS TRANS_HR,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_BREWED_DEPT = 1 THEN POS.LINE_ITEM_QTY ELSE 0 END)/9 AS N_BREWED,
  COUNT(DISTINCT CASE WHEN ITM.IS_MOD = 0 THEN POS.TRANS_LINE_NUM ELSE NULL END) AS N_ITEMS,
  --PRICE PER OZ CALCULATION
  --PRICE PER OZ HOT
  --PRICE PER OZ COLD
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 
           THEN POS.GROSS_SALES_LCL_AMT
           ELSE 0 END)/9
    AS HOT_BEV_GROSS,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 
           THEN POS.NET_REV_LCL_AMT
           ELSE 0 END)/9
    AS HOT_BEV_NDS,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 
           THEN POS.GROSS_SALES_LCL_AMT
           ELSE 0 END)/9
    AS COLD_BEV_GROSS,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 
           THEN POS.NET_REV_LCL_AMT
           ELSE 0 END)/9
    AS COLD_BEV_NDS,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_SHORT = 1 
           THEN 8 
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_TALL = 1
           THEN 12
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_GRANDE = 1
           THEN 16
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_VENTI = 1
           THEN 24
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_TRENTA = 1
           THEN 30
           ELSE NULL END)/9
           AS COLD_OZ,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_SHORT = 1 
           THEN 8 
           WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_TALL = 1
           THEN 12
           WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_GRANDE = 1
           THEN 16
           WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_VENTI = 1
           THEN 24
           ELSE NULL END)/9
           AS HOT_OZ,
  --BREWED ONLY HOT AND COLD OZ
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_SHORT = 1 AND ITM.IS_BREWED_BEV =1
           THEN 8 
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_TALL = 1 AND ITM.IS_BREWED_BEV =1
           THEN 12
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_GRANDE = 1 AND ITM.IS_BREWED_BEV =1
           THEN 16
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_VENTI = 1 AND ITM.IS_BREWED_BEV =1
           THEN 24
           WHEN ITM.IS_MOD = 0 AND ITM.IS_COLD_BEV = 1 AND ITM.IS_TRENTA = 1 AND ITM.IS_BREWED_BEV =1
           THEN 30
           ELSE NULL END)/9
           AS BREWED_COLD_OZ,
  SUM(CASE WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_SHORT = 1  AND ITM.IS_BREWED_BEV =1
           THEN 8 
           WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_TALL = 1 AND ITM.IS_BREWED_BEV =1
           THEN 12
           WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_GRANDE = 1 AND ITM.IS_BREWED_BEV =1
           THEN 16
           WHEN ITM.IS_MOD = 0 AND ITM.IS_HOT_BEV = 1 AND ITM.IS_VENTI = 1 AND ITM.IS_BREWED_BEV =1
           THEN 24
           ELSE NULL END)/9
           AS BREWED_HOT_OZ,
  COUNT(*)
  FROM APPOTHER.AFT_CV_SRVY_RSPNS S
  LEFT OUTER JOIN APPOTHER.CUST_INS_WEIGHTS W
  ON S.CASE_ID = W.CASE_ID
  LEFT OUTER JOIN APPCA.D_STORE_VERS STR
  ON S.STORE_NUM = STR.STORE_NUM
  LEFT OUTER JOIN APPCA.F_POS_LINE_ITEM POS
  ON to_char(S.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(S.STORE_NUM, '000000'))|| ltrim(TO_CHAR(S.RGSTR_NUM, '00')) || TRIM(to_char(S.TRANS_ID)) = POS.TRANS_ID
  LEFT OUTER JOIN D_ITEM_RTL_AUX ITM
  ON POS.ITEM_ID = ITM.ITEM_ID
  LEFT OUTER JOIN D_ITEM ITM1
  ON POS.ITEM_ID = ITM1.ITEM_ID
  WHERE S.RSPNS_DT>=TO_DATE('11/01/2016', 'MM/DD/YYYY')
  AND STR.OWNR_TYPE_CD = 'CO'
  AND STR.CNTRY_CD_2_DGT_ISO = 'US'
  AND STR.CURRENT_FLG = 'Y'
  AND S.CASE_ID = '01201610271003500005429846'
  GROUP BY S.CASE_ID,
  S.GUID_USER_ID,
  S.RSPNS_DT,
  S.TRANS_DTM,
  S.STORE_NUM, 
  S.RGSTR_NUM, 
  S.TRANS_ID,
  SUBSTR(TRIM(TO_CHAR(POS.TRANS_END_TM_KEY, '000000')),1,2)
  
/*
  select 
  IS_BREWED_BEV
  ,IS_BLENDED_BEV
  ,IS_FRAPPBEV
  ,IS_FOOD_CATEGORY
 from D_ITEM_RTL_AUX 
*/