WITH SQ AS (
SELECT dept_descr
,sub_dept_descr
,pkg_sz_qty
,item_descr
,prod_type_descr 
,(CASE WHEN dept_descr='ESPRESSO BEVERAGES' and sub_dept_descr='ESPRESSO BEVERAGES' and prod_type_descr in('LATTE','MACCHIATO') and pkg_sz_qty in ('VENTI',' GRANDE') THEN 'GVLM'
    WHEN sub_dept_descr in ('FRAPPUCCINO BLENDED COFFE','FRAPPUCCINO BLENDED CREME','FRAPPUCCINO BLENDED LIGHT') and pkg_sz_qty in ('GRANDE') THEN 'GFRAPP'
    WHEN sub_dept_descr in ('FRAPPUCCINO BLENDED COFFE','FRAPPUCCINO BLENDED CREME','FRAPPUCCINO BLENDED LIGHT') and pkg_sz_qty in ('VENTI','GRANDE') THEN 'GVFRAPP'
    ELSE NULL END) AS ITEM_SKU1
,(CASE WHEN dept_descr='ESPRESSO BEVERAGES' and pkg_sz_qty in ('VENTI',' GRANDE') THEN 'GVE'
    ELSE NULL END) AS ITEM_SKU2
FROM appca.d_item

GROUP BY
dept_descr
,sub_dept_descr
,pkg_sz_qty
,item_descr
,prod_type_descr)
SELECT COUNT(*) AS TOTAL_ITEMS
,ITEM_SKU1
,ITEM_SKU2
FROM SQ
WHERE (ITEM_SKU1 IS NOT NULL OR ITEM_SKU2 IS NOT NULL)
GROUP BY
ITEM_SKU1
,ITEM_SKU2



LEFT OUTER JOIN APPCA.F_POS_LINE_ITEM POS
  ON to_char(S.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(S.STORE_NUM, '000000'))|| ltrim(TO_CHAR(S.RGSTR_NUM, '00')) || TRIM(to_char(S.TRANS_ID)) = POS.TRANS_ID
  LEFT OUTER JOIN appca.d_item ITM
  ON POS.ITEM_ID = ITM.ITEM_ID

 
 
 
 
 
 
 
 SELECT S.CASE_ID,
  S.GUID_USER_ID,
  S.RSPNS_DT,
  S.TRANS_DTM,
  S.STORE_NUM, 
  S.RGSTR_NUM, 
  S.TRANS_ID,
  (CASE WHEN S.QSTN_ID = 'Q2_1' THEN RSPNS_ID END) AS Q2_1,
  (CASE WHEN S.QSTN_ID = 'Q2_2' THEN RSPNS_ID END) AS Q2_2,
  (CASE WHEN S.QSTN_ID = 'Q2_3' THEN RSPNS_ID END) AS Q2_3,
  (CASE WHEN S.QSTN_ID = 'Q2_4' THEN RSPNS_ID END) AS Q2_4,
  (CASE WHEN S.QSTN_ID = 'Q2_5' THEN RSPNS_ID END) AS Q2_5,
  (CASE WHEN S.QSTN_ID = 'Q2_6' THEN RSPNS_ID END) AS Q2_6,
  (CASE WHEN S.QSTN_ID = 'Q2_7' THEN RSPNS_ID END) AS Q2_7,
  (CASE WHEN S.QSTN_ID = 'Q2_8' THEN RSPNS_ID END) AS Q2_8
  ,SUM(CASE WHEN ITM.dept_descr='ESPRESSO BEVERAGES' and ITM.pkg_sz_qty in ('VENTI',' GRANDE') THEN 1 ELSE 0 END) AS ITEM_SKU2
  ,COUNT(*)
  FROM APPOTHER.AFT_CV_SRVY_RSPNS S
  --LEFT OUTER JOIN APPCA.D_STORE_VERS STR
  --ON S.STORE_NUM = STR.STORE_NUM
  LEFT OUTER JOIN APPCA.F_POS_LINE_ITEM POS
  ON to_char(S.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(S.STORE_NUM, '000000'))|| ltrim(TO_CHAR(S.RGSTR_NUM, '00')) || TRIM(to_char(S.TRANS_ID)) = POS.TRANS_ID
  LEFT OUTER JOIN appca.d_item ITM
  ON POS.ITEM_ID = ITM.ITEM_ID
  --LEFT OUTER JOIN D_ITEM_RTL_AUX ITM1
  --ON POS.ITEM_ID = ITM1.ITEM_ID
  --LEFT OUTER JOIN D_ITEM ITM2
  --ON POS.ITEM_ID = ITM2.ITEM_ID
  WHERE S.RSPNS_DT>=TO_DATE('07/01/2018', 'MM/DD/YYYY')
  --AND STR.OWNR_TYPE_CD = 'CO'
  --AND STR.CNTRY_CD_2_DGT_ISO = 'US'
  --AND STR.CURRENT_FLG = 'Y'
  GROUP BY S.CASE_ID,
  S.GUID_USER_ID,
  S.RSPNS_DT,
  S.TRANS_DTM,
  S.STORE_NUM, 
  S.RGSTR_NUM, 
  S.TRANS_ID
  --SUBSTR(TRIM(TO_CHAR(POS.TRANS_END_TM_KEY, '000000')),1,2)