--SBP415 (PDW)

SELECT 
  COUNT(CASE WHEN sr.QUESTION_ID = 'Q1' THEN sr.QUESTION_ID END) AS Q1_RESP
, SUM(CASE WHEN sr.RESP_ID = '7' AND sr.QUESTION_ID = 'Q1' THEN 1 ELSE 0 END) AS Q1_TB
, ROUND(AVG(CASE WHEN sr.QUESTION_ID = 'Q1' THEN sr.RESP_ID END),2) AS Q1_AVG
, p.STORE_NUM 


FROM APPSTG.SRV_RESPONSES_STG sr
  
LEFT JOIN (
   SELECT * FROM (
    SELECT PRTNR_ID, STORE_NUM,
    ROW_NUMBER() OVER (PARTITION BY PRTNR_ID ORDER BY ETL_INSERT_DTM DESC) AS mostrec
    FROM APPSTG.SRV_ACTIVE_PARTNERS_STG
    WHERE JOB_ABBREV_NM IN ('barista','shift supv','attendant')
    ) WHERE mostrec = 1
  ) p
ON sr.PRTNR_ID = p.PRTNR_ID

INNER JOIN APPPDW.ADV_CAL c
  ON TRUNC(sr.SEND_DT) = c.CAL_DT

WHERE ((c.FSCL_YR_NUM = 2018 AND c.FSCL_PER_IN_YR_NUM <= 7) or (c.FSCL_YR_NUM = 2017 AND c.FSCL_PER_IN_YR_NUM > 7))
  AND sr.QUESTION_ID = 'Q1'

GROUP BY
 p.STORE_NUM  
