--415
--SM Stability

SELECT
s.FSCL_PER_BEG_DT,
s.ORG_UNIT_NUM,
s.STORE_NUM,
s.SM1YRSTABLE,
s.SM2YRSTABLE

FROM LRIVERS.STOREMANAGERSTABILITY s

/* get most recent rolling 12 report (table updates once per month) */
WHERE s.FSCL_PER_BEG_DT = (select max(FSCL_PER_BEG_DT) from LRIVERS.STOREMANAGERSTABILITY)

GROUP BY
s.FSCL_PER_BEG_DT,
s.ORG_UNIT_NUM,
s.STORE_NUM,
s.SM1YRSTABLE,
s.SM2YRSTABLE
