/* SR Transaction Percent by Store */

WITH SQ AS
(SELECT
   ss.STORE_NUM
  ,ca.FSCL_YR_NUM
  ,tr.TRANS_ID
  ,(CASE WHEN tr.GUID_ID = '0' THEN 0 ELSE 1 END) AS SR_MEMBER

FROM APPCA.F_POS_HDR tr

INNER JOIN D_POS_HDR_TRANS_TYPE ty
  ON tr.POS_HDR_TRANS_TYPE_KEY = ty.POS_HDR_TRANS_TYPE_KEY
  
INNER JOIN APPCA.D_STORE_VERS ss
  ON ss.STORE_VERS_KEY = tr.STORE_VERS_KEY
  
INNER JOIN APPCA.D_CAL ca
  ON tr.BUS_DT = ca.CAL_DT

WHERE ss.CNTRY_CD_2_DGT_ISO = 'US'
  AND ss.OWNR_TYPE_CD = 'CO'
  AND ss.STORE_OPEN_DT < '29-JUN-15'  -- beginning of Q4FY15
  AND ca.FSCL_YR_NUM IN (2017,2018) 
  AND ca.FSCL_WK_IN_YR_NUM IN (30,31,32,33)
  --AND ss.STORE_NUM IN (101,104)

GROUP BY
   ss.STORE_NUM
  ,ca.FSCL_YR_NUM
  ,tr.TRANS_ID
  ,tr.GUID_ID), SQ2 AS(
SELECT 
   SQ.STORE_NUM
  ,SQ.FSCL_YR_NUM
  --,COUNT(DISTINCT CASE WHEN SQ.SR_MEMBER = 1 THEN SQ.TRANS_ID ELSE 0 END) AS SR_TRANS_CNT
  --,COUNT(DISTINCT SQ.TRANS_ID) AS TTL_TRANS_CNT
  ,ROUND(COUNT(DISTINCT CASE WHEN SQ.SR_MEMBER = 1 THEN SQ.TRANS_ID ELSE 0 END) / COUNT(DISTINCT SQ.TRANS_ID),4) AS SR_PCT
  
FROM SQ

GROUP BY
   SQ.STORE_NUM
  ,SQ.FSCL_YR_NUM

ORDER BY
   SQ.FSCL_YR_NUM ASC
   ,SQ.STORE_NUM DESC), SQ3 AS(
SELECT
    SQ2.FSCL_YR_NUM
    ,SQ2.STORE_NUM
    ,SQ2.SR_PCT
    ,SQ2.SR_PCT - lag(SQ2.SR_PCT) over(order by SQ2.STORE_NUM, SQ2.FSCL_YR_NUM) AS SR_PCT_YOY_DELTA
FROM SQ2
ORDER BY
    SQ2.FSCL_YR_NUM DESC
    ,SQ2.STORE_NUM DESC) 
SELECT 
    SQ3.STORE_NUM
    ,SQ3.SR_PCT
    ,SQ3.SR_PCT_YOY_DELTA
FROM SQ3
    WHERE SQ3.FSCL_YR_NUM = 2018
