/* SR Transaction Percent by Store */

WITH SQ AS
(SELECT
   ss.STORE_NUM
  ,ss.DRIVE_THRU_IND
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,tr.TRANS_ID
  ,(CASE WHEN tr.GUID_ID = '0' THEN 0 ELSE 1 END) AS SR_MEMBER

FROM APPCA.F_POS_HDR tr

INNER JOIN D_POS_HDR_TRANS_TYPE ty
  ON tr.POS_HDR_TRANS_TYPE_KEY = ty.POS_HDR_TRANS_TYPE_KEY
  
INNER JOIN APPCA.D_STORE_VERS ss
  ON ss.STORE_VERS_KEY = tr.STORE_VERS_KEY
  
INNER JOIN APPCA.D_CAL ca
  ON tr.BUS_DT = ca.CAL_DT

WHERE ss.CNTRY_CD_2_DGT_ISO = 'US'
  AND ss.OWNR_TYPE_CD = 'CO'
  AND ss.STORE_OPEN_DT < '29-JUN-15'  -- beginning of Q4FY15
  AND ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 1

GROUP BY
   ss.STORE_NUM
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,ss.DRIVE_THRU_IND
  ,tr.TRANS_ID
  ,tr.GUID_ID)
SELECT 
   SQ.STORE_NUM
  ,SQ.DRIVE_THRU_IND
  ,SQ.FSCL_YR_NUM
  ,SQ.FSCL_QTR_IN_YR_NUM
  ,SQ.SR_MEMBER
  ,COUNT(DISTINCT SQ.TRANS_ID) AS TTL_TRANS_CNT
  
FROM SQ

GROUP BY
   SQ.STORE_NUM
  ,SQ.DRIVE_THRU_IND
  ,SQ.FSCL_YR_NUM
  ,SQ.FSCL_QTR_IN_YR_NUM
  ,SQ.SR_MEMBER

ORDER BY
   SQ.STORE_NUM
  ,SQ.SR_MEMBER