
/*customer transaction count by hour (and daypart indicator)*/
SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.SALE_HOUR 
  ,f.STORE_NUMBER
  ,r.RGN_ORG_LVL_DESCR
  ,SUM(f.CUTOMER_TRANSACTION_COUNT) AS "TRANS"
      ,(CASE WHEN f.SALE_HOUR  < 110000 THEN 1 -- am
        WHEN f.SALE_HOUR  >=110000 AND f.SALE_HOUR  < 140000 THEN 2 -- midday
        WHEN f.SALE_HOUR  >=140000 AND f.SALE_HOUR  < 160000 THEN 3 -- pm
        WHEN f.SALE_HOUR  >=160000 THEN 4 -- evening
        ELSE 0 
        END) AS DAY_PART
FROM APPBUS.AFT_POS_INTL_HDR_VW f
    INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ((ca.FSCL_YR_NUM = 2018 AND ca.FSCL_QTR_IN_YR_NUM = 1) OR ca.FSCL_YR_NUM = 2017)
        AND f.COUNTRY_CODE = 'US'
    INNER JOIN APPDWH.DDM_RETAIL_ORG_STORE_DIST r
        ON f.STORE_NUMBER = r.STORE_NUM
GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ,f.SALE_HOUR
  ,f.STORE_NUMBER
  ,r.RGN_ORG_LVL_DESCR