/* Pulls customer transaction count by GUID for customers in the CE survey data who made an MOP transaction -- from Oliver */
WITH bl AS
(select b.FSCL_YR_NUM
  ,b.FSCL_QTR_IN_YR_NUM
  ,a.GUID_ID
  ,count(*) AS TRANS

from APPCA.F_SVC_FIN_TRANS a

inner join APPCA.D_CAL b 
  on a.BUS_DT = b.CAL_DT

inner join APPCA.D_SVC_TRANS_TYPE c 
  on a.SVC_TRANS_TYPE_KEY = c.SVC_TRANS_TYPE_KEY

inner join (SELECT
  sr.GUID_USER_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)
  
JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'
  
JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    AND pi.BUS_DT >= '01-SEP-15'
    
JOIN APPCA.D_POS_LINE_ITEM_TRANS_TYPE tt
  ON pi.POS_LINE_ITEM_TRANS_TYPE_KEY = tt.POS_LINE_ITEM_TRANS_TYPE_KEY

WHERE ca.FSCL_YR_NUM >= 2017
  --AND ca.FSCL_QTR_IN_YR_NUM = 3
  AND sr.QSTN_ID IN ('Q2_2')
  AND sr.RSPNS_ID <> '9'
  AND tt.ORD_MTHD_CD IN ('MOP')
GROUP BY 
  sr.GUID_USER_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
  ) sq
  
ON a.GUID_ID = sq.GUID_USER_ID
  AND b.FSCL_YR_NUM = sq.FSCL_YR_NUM
  AND b.FSCL_QTR_IN_YR_NUM = sq.FSCL_QTR_IN_YR_NUM

where c.SVC_INTRNL_RQST_NM = 'Redemption' 
  and b.FSCL_YR_NUM >= 2017

group by a.GUID_ID
  ,b.FSCL_YR_NUM
  ,b.FSCL_QTR_IN_YR_NUM) 

SELECT 
  bl.FSCL_YR_NUM
  ,bl.FSCL_QTR_IN_YR_NUM
  ,AVG(bl.TRANS) FROM bl
GROUP BY 
  bl.FSCL_YR_NUM
  ,bl.FSCL_QTR_IN_YR_NUM





/* Pulls GUIDS for customers in the CE survey data who made an MOP transaction */
/*
SELECT
  sr.GUID_USER_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)
  
JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'
  
JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    AND pi.BUS_DT >= '01-SEP-15'
    
JOIN APPCA.D_POS_LINE_ITEM_TRANS_TYPE tt
  ON pi.POS_LINE_ITEM_TRANS_TYPE_KEY = tt.POS_LINE_ITEM_TRANS_TYPE_KEY

WHERE ca.FSCL_YR_NUM >= 2017
  --AND ca.FSCL_QTR_IN_YR_NUM = 3
  AND sr.QSTN_ID IN ('Q2_2')
  AND sr.RSPNS_ID <> '9'
  AND tt.ORD_MTHD_CD IN ('MOP')
GROUP BY 
  sr.GUID_USER_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_QTR_IN_YR_NUM
*/


SELECT * FROM APPCA.F_SVC_FIN_TRANS
SELECT * FROM APPCA.D_SVC_TRANS_TYPE


WITH bl AS
(select b.FSCL_YR_NUM
  ,b.FSCL_PER_IN_YR_NUM
  ,a.GUID_ID
  ,count(*) AS TRANS
  ,sq.TOTAL_TB
  ,sq.TOTAL_RSPNS

from APPCA.F_SVC_FIN_TRANS a

inner join APPCA.D_CAL b 
  on a.BUS_DT = b.CAL_DT

inner join APPCA.D_SVC_TRANS_TYPE c 
  on a.SVC_TRANS_TYPE_KEY = c.SVC_TRANS_TYPE_KEY

inner join (SELECT
  sr.GUID_USER_ID
  ,SUM(CASE  WHEN sr.RSPNS_ID = '7' THEN 1 ELSE 0 END) AS TOTAL_TB
  ,COUNT(*) AS TOTAL_RSPNS
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_PER_IN_YR_NUM
  ,TRUNC(sr.TRANS_DTM) AS SVY_RSPN_DATE
FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)
  
JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'

WHERE ((ca.FSCL_YR_NUM = 2018 and ca.FSCL_PER_IN_YR_NUM <=3) OR (ca.FSCL_YR_NUM = 2017 and ca.FSCL_PER_IN_YR_NUM > 3))
  AND sr.QSTN_ID IN ('Q2_2')
  --AND sr.STORE_NUM = 5798 -- for testing
  AND sr.RSPNS_ID <> '9'
  --AND TRUNC(sr.TRANS_DTM) = '31-OCT-17'
  AND sr.GUID_USER_ID IN ('0A431223-46E3-438C-B301-B9AEDE967A29','6454D29D-5CC3-4809-AD03-4FA2CBCCFF6B','8F959E6B-5B96-4FD9-B699-04CDE1475DC5')
GROUP BY 
  sr.GUID_USER_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_PER_IN_YR_NUM
  ,TRUNC(sr.TRANS_DTM)
  ) sq
  
ON a.GUID_ID = sq.GUID_USER_ID
  AND b.FSCL_YR_NUM = sq.FSCL_YR_NUM
  AND b.FSCL_PER_IN_YR_NUM = sq.FSCL_PER_IN_YR_NUM

where c.SVC_INTRNL_RQST_NM = 'Redemption' 
  AND ((b.FSCL_YR_NUM = 2018  and b.FSCL_PER_IN_YR_NUM <=3) OR (b.FSCL_YR_NUM = 2017 and b.FSCL_PER_IN_YR_NUM > 3))
  --AND a.BUS_DT BETWEEN sq.SVY_RSPN_DATE - 30 AND sq.SVY_RSPN_DATE
  AND sq.GUID_USER_ID IN ('0A431223-46E3-438C-B301-B9AEDE967A29','6454D29D-5CC3-4809-AD03-4FA2CBCCFF6B','8F959E6B-5B96-4FD9-B699-04CDE1475DC5')
group by b.FSCL_YR_NUM
  ,b.FSCL_PER_IN_YR_NUM
  ,a.GUID_ID
  ,sq.TOTAL_TB
  ,sq.TOTAL_RSPNS) 

SELECT 
  bl.FSCL_YR_NUM
  ,bl.FSCL_PER_IN_YR_NUM
  ,count(bl.GUID_ID) AS USER_COUNT
  ,bl.TRANS
  ,sum(bl.TOTAL_TB) AS TB_COUNT
  ,sum(bl.TOTAL_RSPNS) AS RSPSN_COUNT
FROM bl
GROUP BY 
  bl.FSCL_YR_NUM
  ,bl.FSCL_PER_IN_YR_NUM
  ,bl.TRANS
ORDER BY
  bl.FSCL_YR_NUM
  ,bl.FSCL_PER_IN_YR_NUM
  ,bl.TRANS
  
  
  
  
  
  SELECT
   SRVY_TRANS_DT
  ,COUNTRY_CD
  ,SRVYED_STORE_OWNR_TYPE
  ,CO_POS_TRANS_IND
  ,TRANS_CNT
  ,COUNT(*) AS NUMBER_OF_CUSTOMERS
FROM
(
WITH GUID_LIST AS (
  SELECT DISTINCT
     srvy.CASE_ID
    ,UPPER(srvy.GUID_USER_ID) AS GUID
    ,srvy.STORE_NUM
    ,st.CNTRY_CD_2_DGT_ISO AS COUNTRY_CD
    ,st.OWNR_TYPE_CD AS SRVYED_STORE_OWNR_TYPE
    ,TRUNC(srvy.TRANS_DTM) AS SRVY_TRANS_DT
  FROM APPOTHER.AFT_CV_SRVY_RSPNS srvy
  
  LEFT JOIN APPCA.D_STORE_VERS st
    ON srvy.STORE_NUM = st.STORE_NUM
      AND st.CNTRY_CD_2_DGT_ISO IN ('US')
      AND st.STORE_BRAND_CD = 'SBUX'
      AND TRUNC(srvy.TRANS_DTM) BETWEEN st.EFF_FROM_DT AND st.EFF_TO_DT

  WHERE TRUNC(TRANS_DTM) BETWEEN TRUNC(SYSDATE) - 91 AND TRUNC(SYSDATE) - 1
  AND srvy.GUID_USER_ID IN ('0A431223-46E3-438C-B301-B9AEDE967A29','6454D29D-5CC3-4809-AD03-4FA2CBCCFF6B','8F959E6B-5B96-4FD9-B699-04CDE1475DC5')

)

SELECT
   gl.CASE_ID
  ,gl.GUID
  ,gl.SRVY_TRANS_DT
  ,gl.COUNTRY_CD
  ,gl.SRVYED_STORE_OWNR_TYPE
  ,f.CO_POS_TRANS_IND
  ,COUNT(f.TRANS_ID) AS TRANS_CNT
FROM GUID_LIST gl

LEFT JOIN APPCA.F_CARD f
  ON gl.GUID = f.GUID_ID
    AND f.SVC_TRANS_CTGY = 'Redemption'
    AND f.TRANS_DT BETWEEN gl.SRVY_TRANS_DT - 30 AND gl.SRVY_TRANS_DT
    --AND f.TRANS_DT = '30-oct-17'
    AND f.GUID_ID IN ('0A431223-46E3-438C-B301-B9AEDE967A29','6454D29D-5CC3-4809-AD03-4FA2CBCCFF6B','8F959E6B-5B96-4FD9-B699-04CDE1475DC5')
GROUP BY
   gl.CASE_ID
  ,gl.GUID
  ,gl.SRVY_TRANS_DT
  ,gl.COUNTRY_CD
  ,gl.SRVYED_STORE_OWNR_TYPE
  ,f.CO_POS_TRANS_IND
)

GROUP BY
   SRVY_TRANS_DT
  ,COUNTRY_CD
  ,SRVYED_STORE_OWNR_TYPE
  ,CO_POS_TRANS_IND
  ,TRANS_CNT
ORDER BY
   SRVY_TRANS_DT
  ,COUNTRY_CD
  ,SRVYED_STORE_OWNR_TYPE
  ,TRANS_CNT
  
  
  
select * from APPCA.F_CARD f
WHERE f.GUID_ID IN ('0A431223-46E3-438C-B301-B9AEDE967A29','6454D29D-5CC3-4809-AD03-4FA2CBCCFF6B','8F959E6B-5B96-4FD9-B699-04CDE1475DC5')
AND f.SVC_TRANS_CTGY = 'Redemption'
AND f.TRANS_DT >= '01-DEC-17' AND f.TRANS_DT <= '31-DEC-17'
ORDER BY f.GUID_ID, f.TRANS_DT