--411
--customer transactions and net sales by half-hour block

WITH SQ AS
(SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,f.STORE_NUMBER
  ,r.RGN_ORG_LVL_DESCR
  ,SUM(f.CUTOMER_TRANSACTION_COUNT) AS TRANS
  ,SUM(f.NET_SALES_AMT) AS NET_SALES
  ,SUM(f.NET_SALES_UNITS) AS NET_UNITS
  
FROM APPBUS.AFT_POS_INTL_HDR_VW f
    INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM = 2018 
        AND ca.FSCL_WK_IN_YR_NUM = 24
        AND f.COUNTRY_CODE = 'US'
    INNER JOIN APPDWH.DDM_RETAIL_ORG_STORE_DIST r
        ON f.STORE_NUMBER = r.STORE_NUM

WHERE f.SALE_HALF_HOUR BETWEEN 70000 AND 95959 

GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,f.STORE_NUMBER
  ,r.RGN_ORG_LVL_DESCR)
  SELECT SQ.FSCL_YR_NUM
  ,SQ.FSCL_WK_IN_YR_NUM
  ,SQ.STORE_NUMBER
  ,SQ.RGN_ORG_LVL_DESCR
  ,SUM(SQ.TRANS) AS TRANS
  ,SUM(SQ.NET_SALES) AS NET_SALES
   ,SUM(SQ.NET_UNITS) AS NET_UNITS
   
  FROM SQ

  GROUP BY SQ.FSCL_YR_NUM
  ,SQ.FSCL_WK_IN_YR_NUM
  ,SQ.STORE_NUMBER
  ,SQ.RGN_ORG_LVL_DESCR
  
  ORDER BY SQ.FSCL_YR_NUM
  ,SQ.FSCL_WK_IN_YR_NUM
  ,SQ.STORE_NUMBER

