--411
--customer transactions and net sales by half-hour block

WITH SQ AS
(SELECT ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,f.SALE_HALF_HOUR 
  ,f.STORE_NUMBER
  ,SUM(f.CUTOMER_TRANSACTION_COUNT) AS TRANS
  ,SUM(f.NET_SALES_AMT) AS NET_SALES
      ,(CASE WHEN f.SALE_HALF_HOUR  >=80000 AND f.SALE_HALF_HOUR  < 83000 THEN 1 -- 8-8:29:59am
        WHEN f.SALE_HALF_HOUR  >=83000 AND f.SALE_HALF_HOUR  < 90000 THEN 2 -- 8:30-8:59:59am
        WHEN f.SALE_HALF_HOUR  >=90000 AND f.SALE_HALF_HOUR  < 93000 THEN 3 -- 9-9:29:59am
        WHEN f.SALE_HALF_HOUR  >=93000 AND f.SALE_HALF_HOUR  < 100000 THEN 4 -- 9:30-9:59:59am
        ELSE 0 
        END) AS HALF_HOUR_BLOCK
FROM APPBUS.AFT_POS_INTL_HDR_VW f
    INNER JOIN APPDWH.ADT_CAL ca
        ON f.BUSINESS_DATE = ca.CAL_DT
        AND ca.FSCL_YR_NUM = 2018 
        AND ca.FSCL_WK_IN_YR_NUM = 24
        AND f.COUNTRY_CODE = 'US'
    INNER JOIN APPDWH.DDM_RETAIL_ORG_STORE_DIST r
        ON f.STORE_NUMBER = r.STORE_NUM
GROUP BY 
  ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,f.SALE_HALF_HOUR
  ,f.STORE_NUMBER)
  SELECT SQ.FSCL_YR_NUM
  ,SQ.FSCL_WK_IN_YR_NUM
  ,SQ.HALF_HOUR_BLOCK
  ,SQ.STORE_NUMBER
  ,SUM(SQ.TRANS) AS TRANS
  ,SUM(SQ.NET_SALES) AS NET_SALES
  FROM SQ
  WHERE HALF_HOUR_BLOCK > 0 -- remove other time periods
  GROUP BY SQ.FSCL_YR_NUM
  ,SQ.FSCL_WK_IN_YR_NUM
  ,SQ.STORE_NUMBER
  ,SQ.HALF_HOUR_BLOCK
  ORDER BY SQ.FSCL_YR_NUM
  ,SQ.FSCL_WK_IN_YR_NUM
  ,SQ.STORE_NUMBER
  ,SQ.HALF_HOUR_BLOCK
