
WITH SQ AS (SELECT ac.GUID_ID, COUNT(*) AS FY17Q4_TRAN FROM APPCA.F_CARD ac
  WHERE ac.TRANS_DT >= '03-JUL-17' AND ac.TRANS_DT <= '01-OCT-17'
  AND ac.SVC_TRANS_CTGY = 'Redemption'
  GROUP BY ac.GUID_ID)
SELECT * FROM SQ
    WHERE FY17Q4_TRAN > 1
    
    
    
    
    
WITH SQ AS (SELECT ac.GUID_ID, COUNT(*) AS NOV17_TRAN FROM APPCA.F_CARD ac
  WHERE ac.TRANS_DT >= '01-NOV-17' AND ac.TRANS_DT <= '30-NOV-17'
  AND ac.SVC_TRANS_CTGY = 'Redemption'
  GROUP BY ac.GUID_ID)
SELECT * FROM SQ
    WHERE NOV17_TRAN > 1